Netarkivet datasheet and application scripts.
centre-for-humanities-computing/danish-foundation-models pull request #129
Opened 2022-05-30 10:02 UTC by KennethEnevoldsen

- [x] include script for pre-processing netarkivet
- [ ] a finalized datasheet (work in progress)
 

2022-06-13 17:01 UTC, saattrupdan commented
Is this ready for review (cf. the non ticked todo box)?

2022-06-13 17:33 UTC, KennethEnevoldsen commented
Yes! (You were just here just before I ticked it 🙃)

2022-06-13 18:47 UTC, saattrupdan commented
Am I reviewing the code, or OS it just the sheet?

2022-06-13 20:08 UTC, saattrupdan requested changes
Looks good! I only have a bunch of typos.

2022-06-13 20:08 UTC, saattrupdan commented on docs/datasheets/Netarkivet_text.md
> +of the development on the Danish Web.
```suggestion
Yes, the dataset has been used to pre-train Danish language models.
Furthermore, the unfiltered dataset has also been used in [4] and [5], for examining
of the development on the Danish web.
```

2022-06-13 20:08 UTC, saattrupdan commented on docs/datasheets/Netarkivet_text.md
> +It is likely possible to extract reviews, social media post and similar semi-labelled
```suggestion
It is likely possible to extract reviews, social media posts and similar semi-labelled
```

2022-06-13 20:08 UTC, saattrupdan commented on docs/datasheets/Netarkivet_text.md
> +dataset going forward.
```suggestion
This dataset is static and thus does not evolve over time with the language, thus will
become increasingly outdated over time. Netarkivet, from which it is derived, is
not static however, and is thus likely to further develop, which will allow us to update the 
dataset going forward.
```

2022-06-13 20:08 UTC, saattrupdan commented on src/applications/netarkivet/apply_filters.py
> +    """
If you want to do Google-style docstrings you should include a blank line between the headings:
```suggestion
    """Creates shuffle buffer from iterable.
    
    Args:
        x (Iterable): An iterable you want shuffled
        buffer_size (int): The buffer shuffle
    
    Returns:
        Iterable: An iterable which is shuffled using a shuffle buffer
    
    Example:
        >>> shuffled = shuffle_buffer(x =[1,2, 3, 4, 5], buffer_size=2)
        >>> print(list(shuffled))
        [2, 1, 4, 3, 5]
    """
```

2022-06-18 08:46 UTC, KennethEnevoldsen commented
<!-- Pytest Coverage Comment: pytest-coverage -->
<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/b4d08481e535dd4794f786ec1a31c4972379e383/README.md"><img alt="Coverage" src="https://img.shields.io/badge/Coverage-60%25-yellow.svg" /></a><br/><details><summary>Coverage Report</summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>src/dfm</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/b4d08481e535dd4794f786ec1a31c4972379e383/src/dfm/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/b4d08481e535dd4794f786ec1a31c4972379e383/src/dfm/train.py">train.py</a></td><td>68</td><td>68</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/b4d08481e535dd4794f786ec1a31c4972379e383/src/dfm/train.py#L14-L226">14&ndash;226</a></td></tr><tr><td colspan="5"><b>src/dfm/cleaning</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/b4d08481e535dd4794f786ec1a31c4972379e383/src/dfm/cleaning/__init__.py">__init__.py</a></td><td>2</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/b4d08481e535dd4794f786ec1a31c4972379e383/src/dfm/cleaning/deduper.py">deduper.py</a></td><td>156</td><td>16</td><td>90%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/b4d08481e535dd4794f786ec1a31c4972379e383/src/dfm/cleaning/deduper.py#L119-L124">119&ndash;124</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/b4d08481e535dd4794f786ec1a31c4972379e383/src/dfm/cleaning/deduper.py#L147">147</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/b4d08481e535dd4794f786ec1a31c4972379e383/src/dfm/cleaning/deduper.py#L275">275</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/b4d08481e535dd4794f786ec1a31c4972379e383/src/dfm/cleaning/deduper.py#L278">278</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/b4d08481e535dd4794f786ec1a31c4972379e383/src/dfm/cleaning/deduper.py#L311">311</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/b4d08481e535dd4794f786ec1a31c4972379e383/src/dfm/cleaning/deduper.py#L406">406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/b4d08481e535dd4794f786ec1a31c4972379e383/src/dfm/cleaning/deduper.py#L421">421</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/b4d08481e535dd4794f786ec1a31c4972379e383/src/dfm/cleaning/deduper.py#L444">444</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/b4d08481e535dd4794f786ec1a31c4972379e383/src/dfm/cleaning/deduper.py#L549">549</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/b4d08481e535dd4794f786ec1a31c4972379e383/src/dfm/cleaning/deduper.py#L576-L579">576&ndash;579</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/b4d08481e535dd4794f786ec1a31c4972379e383/src/dfm/cleaning/deduper_utils.py">deduper_utils.py</a></td><td>26</td><td>3</td><td>88%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/b4d08481e535dd4794f786ec1a31c4972379e383/src/dfm/cleaning/deduper_utils.py#L57-L60">57&ndash;60</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/b4d08481e535dd4794f786ec1a31c4972379e383/src/dfm/cleaning/quality_filter.py">quality_filter.py</a></td><td>220</td><td>32</td><td>85%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/b4d08481e535dd4794f786ec1a31c4972379e383/src/dfm/cleaning/quality_filter.py#L78-L83">78&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/b4d08481e535dd4794f786ec1a31c4972379e383/src/dfm/cleaning/quality_filter.py#L264">264</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/b4d08481e535dd4794f786ec1a31c4972379e383/src/dfm/cleaning/quality_filter.py#L269">269</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/b4d08481e535dd4794f786ec1a31c4972379e383/src/dfm/cleaning/quality_filter.py#L343">343</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/b4d08481e535dd4794f786ec1a31c4972379e383/src/dfm/cleaning/quality_filter.py#L352">352</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/b4d08481e535dd4794f786ec1a31c4972379e383/src/dfm/cleaning/quality_filter.py#L391-L406">391&ndash;406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/b4d08481e535dd4794f786ec1a31c4972379e383/src/dfm/cleaning/quality_filter.py#L539">539</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/b4d08481e535dd4794f786ec1a31c4972379e383/src/dfm/cleaning/quality_filter.py#L572-L575">572&ndash;575</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/b4d08481e535dd4794f786ec1a31c4972379e383/src/dfm/cleaning/quality_filter.py#L600">600</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/b4d08481e535dd4794f786ec1a31c4972379e383/src/dfm/cleaning/quality_filter.py#L632">632</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/b4d08481e535dd4794f786ec1a31c4972379e383/src/dfm/cleaning/quality_filter.py#L716">716</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/b4d08481e535dd4794f786ec1a31c4972379e383/src/dfm/cleaning/quality_filter.py#L730">730</a></td></tr><tr><td colspan="5"><b>src/dfm/data</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/b4d08481e535dd4794f786ec1a31c4972379e383/src/dfm/data/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/b4d08481e535dd4794f786ec1a31c4972379e383/src/dfm/data/hate_speech.py">hate_speech.py</a></td><td>11</td><td>11</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/b4d08481e535dd4794f786ec1a31c4972379e383/src/dfm/data/hate_speech.py#L1-L20">1&ndash;20</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/b4d08481e535dd4794f786ec1a31c4972379e383/src/dfm/data/load.py">load.py</a></td><td>106</td><td>91</td><td>14%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/b4d08481e535dd4794f786ec1a31c4972379e383/src/dfm/data/load.py#L35-L50">35&ndash;50</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/b4d08481e535dd4794f786ec1a31c4972379e383/src/dfm/data/load.py#L59-L83">59&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/b4d08481e535dd4794f786ec1a31c4972379e383/src/dfm/data/load.py#L98-L119">98&ndash;119</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/b4d08481e535dd4794f786ec1a31c4972379e383/src/dfm [...]

2022-06-18 08:46 UTC, KennethEnevoldsen commented
<!-- Pytest Coverage Comment: pytest-coverage -->
<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/185643bf9e2d7e9e4c44ed3da18336ca7937f98e/README.md"><img alt="Coverage" src="https://img.shields.io/badge/Coverage-60%25-yellow.svg" /></a><br/><details><summary>Coverage Report</summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>src/dfm</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/185643bf9e2d7e9e4c44ed3da18336ca7937f98e/src/dfm/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/185643bf9e2d7e9e4c44ed3da18336ca7937f98e/src/dfm/train.py">train.py</a></td><td>68</td><td>68</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/185643bf9e2d7e9e4c44ed3da18336ca7937f98e/src/dfm/train.py#L14-L226">14&ndash;226</a></td></tr><tr><td colspan="5"><b>src/dfm/cleaning</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/185643bf9e2d7e9e4c44ed3da18336ca7937f98e/src/dfm/cleaning/__init__.py">__init__.py</a></td><td>2</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/185643bf9e2d7e9e4c44ed3da18336ca7937f98e/src/dfm/cleaning/deduper.py">deduper.py</a></td><td>156</td><td>16</td><td>90%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/185643bf9e2d7e9e4c44ed3da18336ca7937f98e/src/dfm/cleaning/deduper.py#L119-L124">119&ndash;124</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/185643bf9e2d7e9e4c44ed3da18336ca7937f98e/src/dfm/cleaning/deduper.py#L147">147</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/185643bf9e2d7e9e4c44ed3da18336ca7937f98e/src/dfm/cleaning/deduper.py#L275">275</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/185643bf9e2d7e9e4c44ed3da18336ca7937f98e/src/dfm/cleaning/deduper.py#L278">278</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/185643bf9e2d7e9e4c44ed3da18336ca7937f98e/src/dfm/cleaning/deduper.py#L311">311</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/185643bf9e2d7e9e4c44ed3da18336ca7937f98e/src/dfm/cleaning/deduper.py#L406">406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/185643bf9e2d7e9e4c44ed3da18336ca7937f98e/src/dfm/cleaning/deduper.py#L421">421</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/185643bf9e2d7e9e4c44ed3da18336ca7937f98e/src/dfm/cleaning/deduper.py#L444">444</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/185643bf9e2d7e9e4c44ed3da18336ca7937f98e/src/dfm/cleaning/deduper.py#L549">549</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/185643bf9e2d7e9e4c44ed3da18336ca7937f98e/src/dfm/cleaning/deduper.py#L576-L579">576&ndash;579</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/185643bf9e2d7e9e4c44ed3da18336ca7937f98e/src/dfm/cleaning/deduper_utils.py">deduper_utils.py</a></td><td>26</td><td>3</td><td>88%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/185643bf9e2d7e9e4c44ed3da18336ca7937f98e/src/dfm/cleaning/deduper_utils.py#L57-L60">57&ndash;60</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/185643bf9e2d7e9e4c44ed3da18336ca7937f98e/src/dfm/cleaning/quality_filter.py">quality_filter.py</a></td><td>220</td><td>32</td><td>85%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/185643bf9e2d7e9e4c44ed3da18336ca7937f98e/src/dfm/cleaning/quality_filter.py#L78-L83">78&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/185643bf9e2d7e9e4c44ed3da18336ca7937f98e/src/dfm/cleaning/quality_filter.py#L264">264</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/185643bf9e2d7e9e4c44ed3da18336ca7937f98e/src/dfm/cleaning/quality_filter.py#L269">269</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/185643bf9e2d7e9e4c44ed3da18336ca7937f98e/src/dfm/cleaning/quality_filter.py#L343">343</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/185643bf9e2d7e9e4c44ed3da18336ca7937f98e/src/dfm/cleaning/quality_filter.py#L352">352</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/185643bf9e2d7e9e4c44ed3da18336ca7937f98e/src/dfm/cleaning/quality_filter.py#L391-L406">391&ndash;406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/185643bf9e2d7e9e4c44ed3da18336ca7937f98e/src/dfm/cleaning/quality_filter.py#L539">539</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/185643bf9e2d7e9e4c44ed3da18336ca7937f98e/src/dfm/cleaning/quality_filter.py#L572-L575">572&ndash;575</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/185643bf9e2d7e9e4c44ed3da18336ca7937f98e/src/dfm/cleaning/quality_filter.py#L600">600</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/185643bf9e2d7e9e4c44ed3da18336ca7937f98e/src/dfm/cleaning/quality_filter.py#L632">632</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/185643bf9e2d7e9e4c44ed3da18336ca7937f98e/src/dfm/cleaning/quality_filter.py#L716">716</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/185643bf9e2d7e9e4c44ed3da18336ca7937f98e/src/dfm/cleaning/quality_filter.py#L730">730</a></td></tr><tr><td colspan="5"><b>src/dfm/data</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/185643bf9e2d7e9e4c44ed3da18336ca7937f98e/src/dfm/data/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/185643bf9e2d7e9e4c44ed3da18336ca7937f98e/src/dfm/data/hate_speech.py">hate_speech.py</a></td><td>11</td><td>11</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/185643bf9e2d7e9e4c44ed3da18336ca7937f98e/src/dfm/data/hate_speech.py#L1-L20">1&ndash;20</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/185643bf9e2d7e9e4c44ed3da18336ca7937f98e/src/dfm/data/load.py">load.py</a></td><td>106</td><td>91</td><td>14%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/185643bf9e2d7e9e4c44ed3da18336ca7937f98e/src/dfm/data/load.py#L35-L50">35&ndash;50</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/185643bf9e2d7e9e4c44ed3da18336ca7937f98e/src/dfm/data/load.py#L59-L83">59&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/185643bf9e2d7e9e4c44ed3da18336ca7937f98e/src/dfm/data/load.py#L98-L119">98&ndash;119</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/185643bf9e2d7e9e4c44ed3da18336ca7937f98e/src/dfm [...]

2022-06-18 08:46 UTC, KennethEnevoldsen commented
<!-- Pytest Coverage Comment: pytest-coverage -->
<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/f6a5f54b59c8eea2450213cdf1cdead4d3fc6917/README.md"><img alt="Coverage" src="https://img.shields.io/badge/Coverage-60%25-yellow.svg" /></a><br/><details><summary>Coverage Report</summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>src/dfm</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/f6a5f54b59c8eea2450213cdf1cdead4d3fc6917/src/dfm/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/f6a5f54b59c8eea2450213cdf1cdead4d3fc6917/src/dfm/train.py">train.py</a></td><td>68</td><td>68</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/f6a5f54b59c8eea2450213cdf1cdead4d3fc6917/src/dfm/train.py#L14-L226">14&ndash;226</a></td></tr><tr><td colspan="5"><b>src/dfm/cleaning</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/f6a5f54b59c8eea2450213cdf1cdead4d3fc6917/src/dfm/cleaning/__init__.py">__init__.py</a></td><td>2</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/f6a5f54b59c8eea2450213cdf1cdead4d3fc6917/src/dfm/cleaning/deduper.py">deduper.py</a></td><td>156</td><td>16</td><td>90%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/f6a5f54b59c8eea2450213cdf1cdead4d3fc6917/src/dfm/cleaning/deduper.py#L119-L124">119&ndash;124</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/f6a5f54b59c8eea2450213cdf1cdead4d3fc6917/src/dfm/cleaning/deduper.py#L147">147</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/f6a5f54b59c8eea2450213cdf1cdead4d3fc6917/src/dfm/cleaning/deduper.py#L275">275</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/f6a5f54b59c8eea2450213cdf1cdead4d3fc6917/src/dfm/cleaning/deduper.py#L278">278</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/f6a5f54b59c8eea2450213cdf1cdead4d3fc6917/src/dfm/cleaning/deduper.py#L311">311</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/f6a5f54b59c8eea2450213cdf1cdead4d3fc6917/src/dfm/cleaning/deduper.py#L406">406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/f6a5f54b59c8eea2450213cdf1cdead4d3fc6917/src/dfm/cleaning/deduper.py#L421">421</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/f6a5f54b59c8eea2450213cdf1cdead4d3fc6917/src/dfm/cleaning/deduper.py#L444">444</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/f6a5f54b59c8eea2450213cdf1cdead4d3fc6917/src/dfm/cleaning/deduper.py#L549">549</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/f6a5f54b59c8eea2450213cdf1cdead4d3fc6917/src/dfm/cleaning/deduper.py#L576-L579">576&ndash;579</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/f6a5f54b59c8eea2450213cdf1cdead4d3fc6917/src/dfm/cleaning/deduper_utils.py">deduper_utils.py</a></td><td>26</td><td>3</td><td>88%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/f6a5f54b59c8eea2450213cdf1cdead4d3fc6917/src/dfm/cleaning/deduper_utils.py#L57-L60">57&ndash;60</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/f6a5f54b59c8eea2450213cdf1cdead4d3fc6917/src/dfm/cleaning/quality_filter.py">quality_filter.py</a></td><td>220</td><td>32</td><td>85%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/f6a5f54b59c8eea2450213cdf1cdead4d3fc6917/src/dfm/cleaning/quality_filter.py#L78-L83">78&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/f6a5f54b59c8eea2450213cdf1cdead4d3fc6917/src/dfm/cleaning/quality_filter.py#L264">264</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/f6a5f54b59c8eea2450213cdf1cdead4d3fc6917/src/dfm/cleaning/quality_filter.py#L269">269</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/f6a5f54b59c8eea2450213cdf1cdead4d3fc6917/src/dfm/cleaning/quality_filter.py#L343">343</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/f6a5f54b59c8eea2450213cdf1cdead4d3fc6917/src/dfm/cleaning/quality_filter.py#L352">352</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/f6a5f54b59c8eea2450213cdf1cdead4d3fc6917/src/dfm/cleaning/quality_filter.py#L391-L406">391&ndash;406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/f6a5f54b59c8eea2450213cdf1cdead4d3fc6917/src/dfm/cleaning/quality_filter.py#L539">539</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/f6a5f54b59c8eea2450213cdf1cdead4d3fc6917/src/dfm/cleaning/quality_filter.py#L572-L575">572&ndash;575</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/f6a5f54b59c8eea2450213cdf1cdead4d3fc6917/src/dfm/cleaning/quality_filter.py#L600">600</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/f6a5f54b59c8eea2450213cdf1cdead4d3fc6917/src/dfm/cleaning/quality_filter.py#L632">632</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/f6a5f54b59c8eea2450213cdf1cdead4d3fc6917/src/dfm/cleaning/quality_filter.py#L716">716</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/f6a5f54b59c8eea2450213cdf1cdead4d3fc6917/src/dfm/cleaning/quality_filter.py#L730">730</a></td></tr><tr><td colspan="5"><b>src/dfm/data</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/f6a5f54b59c8eea2450213cdf1cdead4d3fc6917/src/dfm/data/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/f6a5f54b59c8eea2450213cdf1cdead4d3fc6917/src/dfm/data/hate_speech.py">hate_speech.py</a></td><td>11</td><td>11</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/f6a5f54b59c8eea2450213cdf1cdead4d3fc6917/src/dfm/data/hate_speech.py#L1-L20">1&ndash;20</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/f6a5f54b59c8eea2450213cdf1cdead4d3fc6917/src/dfm/data/load.py">load.py</a></td><td>106</td><td>91</td><td>14%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/f6a5f54b59c8eea2450213cdf1cdead4d3fc6917/src/dfm/data/load.py#L35-L50">35&ndash;50</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/f6a5f54b59c8eea2450213cdf1cdead4d3fc6917/src/dfm/data/load.py#L59-L83">59&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/f6a5f54b59c8eea2450213cdf1cdead4d3fc6917/src/dfm/data/load.py#L98-L119">98&ndash;119</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/f6a5f54b59c8eea2450213cdf1cdead4d3fc6917/src/dfm [...]

2022-06-18 08:46 UTC, KennethEnevoldsen commented
<!-- Pytest Coverage Comment: pytest-coverage -->
<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/32ad72b20c8bc8f0aa6f28cbb64659136aeb5e14/README.md"><img alt="Coverage" src="https://img.shields.io/badge/Coverage-60%25-yellow.svg" /></a><br/><details><summary>Coverage Report</summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>src/dfm</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/32ad72b20c8bc8f0aa6f28cbb64659136aeb5e14/src/dfm/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/32ad72b20c8bc8f0aa6f28cbb64659136aeb5e14/src/dfm/train.py">train.py</a></td><td>68</td><td>68</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/32ad72b20c8bc8f0aa6f28cbb64659136aeb5e14/src/dfm/train.py#L14-L226">14&ndash;226</a></td></tr><tr><td colspan="5"><b>src/dfm/cleaning</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/32ad72b20c8bc8f0aa6f28cbb64659136aeb5e14/src/dfm/cleaning/__init__.py">__init__.py</a></td><td>2</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/32ad72b20c8bc8f0aa6f28cbb64659136aeb5e14/src/dfm/cleaning/deduper.py">deduper.py</a></td><td>156</td><td>16</td><td>90%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/32ad72b20c8bc8f0aa6f28cbb64659136aeb5e14/src/dfm/cleaning/deduper.py#L119-L124">119&ndash;124</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/32ad72b20c8bc8f0aa6f28cbb64659136aeb5e14/src/dfm/cleaning/deduper.py#L147">147</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/32ad72b20c8bc8f0aa6f28cbb64659136aeb5e14/src/dfm/cleaning/deduper.py#L275">275</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/32ad72b20c8bc8f0aa6f28cbb64659136aeb5e14/src/dfm/cleaning/deduper.py#L278">278</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/32ad72b20c8bc8f0aa6f28cbb64659136aeb5e14/src/dfm/cleaning/deduper.py#L311">311</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/32ad72b20c8bc8f0aa6f28cbb64659136aeb5e14/src/dfm/cleaning/deduper.py#L406">406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/32ad72b20c8bc8f0aa6f28cbb64659136aeb5e14/src/dfm/cleaning/deduper.py#L421">421</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/32ad72b20c8bc8f0aa6f28cbb64659136aeb5e14/src/dfm/cleaning/deduper.py#L444">444</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/32ad72b20c8bc8f0aa6f28cbb64659136aeb5e14/src/dfm/cleaning/deduper.py#L549">549</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/32ad72b20c8bc8f0aa6f28cbb64659136aeb5e14/src/dfm/cleaning/deduper.py#L576-L579">576&ndash;579</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/32ad72b20c8bc8f0aa6f28cbb64659136aeb5e14/src/dfm/cleaning/deduper_utils.py">deduper_utils.py</a></td><td>26</td><td>3</td><td>88%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/32ad72b20c8bc8f0aa6f28cbb64659136aeb5e14/src/dfm/cleaning/deduper_utils.py#L57-L60">57&ndash;60</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/32ad72b20c8bc8f0aa6f28cbb64659136aeb5e14/src/dfm/cleaning/quality_filter.py">quality_filter.py</a></td><td>220</td><td>32</td><td>85%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/32ad72b20c8bc8f0aa6f28cbb64659136aeb5e14/src/dfm/cleaning/quality_filter.py#L78-L83">78&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/32ad72b20c8bc8f0aa6f28cbb64659136aeb5e14/src/dfm/cleaning/quality_filter.py#L264">264</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/32ad72b20c8bc8f0aa6f28cbb64659136aeb5e14/src/dfm/cleaning/quality_filter.py#L269">269</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/32ad72b20c8bc8f0aa6f28cbb64659136aeb5e14/src/dfm/cleaning/quality_filter.py#L343">343</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/32ad72b20c8bc8f0aa6f28cbb64659136aeb5e14/src/dfm/cleaning/quality_filter.py#L352">352</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/32ad72b20c8bc8f0aa6f28cbb64659136aeb5e14/src/dfm/cleaning/quality_filter.py#L391-L406">391&ndash;406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/32ad72b20c8bc8f0aa6f28cbb64659136aeb5e14/src/dfm/cleaning/quality_filter.py#L539">539</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/32ad72b20c8bc8f0aa6f28cbb64659136aeb5e14/src/dfm/cleaning/quality_filter.py#L572-L575">572&ndash;575</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/32ad72b20c8bc8f0aa6f28cbb64659136aeb5e14/src/dfm/cleaning/quality_filter.py#L600">600</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/32ad72b20c8bc8f0aa6f28cbb64659136aeb5e14/src/dfm/cleaning/quality_filter.py#L632">632</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/32ad72b20c8bc8f0aa6f28cbb64659136aeb5e14/src/dfm/cleaning/quality_filter.py#L716">716</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/32ad72b20c8bc8f0aa6f28cbb64659136aeb5e14/src/dfm/cleaning/quality_filter.py#L730">730</a></td></tr><tr><td colspan="5"><b>src/dfm/data</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/32ad72b20c8bc8f0aa6f28cbb64659136aeb5e14/src/dfm/data/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/32ad72b20c8bc8f0aa6f28cbb64659136aeb5e14/src/dfm/data/hate_speech.py">hate_speech.py</a></td><td>11</td><td>11</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/32ad72b20c8bc8f0aa6f28cbb64659136aeb5e14/src/dfm/data/hate_speech.py#L1-L20">1&ndash;20</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/32ad72b20c8bc8f0aa6f28cbb64659136aeb5e14/src/dfm/data/load.py">load.py</a></td><td>106</td><td>91</td><td>14%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/32ad72b20c8bc8f0aa6f28cbb64659136aeb5e14/src/dfm/data/load.py#L35-L50">35&ndash;50</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/32ad72b20c8bc8f0aa6f28cbb64659136aeb5e14/src/dfm/data/load.py#L59-L83">59&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/32ad72b20c8bc8f0aa6f28cbb64659136aeb5e14/src/dfm/data/load.py#L98-L119">98&ndash;119</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/32ad72b20c8bc8f0aa6f28cbb64659136aeb5e14/src/dfm [...]

2022-06-18 08:46 UTC, KennethEnevoldsen commented
<!-- Pytest Coverage Comment: pytest-coverage -->
<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0f5a1b308dbd713a213db413b4b4e430cc75a89c/README.md"><img alt="Coverage" src="https://img.shields.io/badge/Coverage-60%25-yellow.svg" /></a><br/><details><summary>Coverage Report</summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>src/dfm</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0f5a1b308dbd713a213db413b4b4e430cc75a89c/src/dfm/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0f5a1b308dbd713a213db413b4b4e430cc75a89c/src/dfm/train.py">train.py</a></td><td>68</td><td>68</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0f5a1b308dbd713a213db413b4b4e430cc75a89c/src/dfm/train.py#L14-L226">14&ndash;226</a></td></tr><tr><td colspan="5"><b>src/dfm/cleaning</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0f5a1b308dbd713a213db413b4b4e430cc75a89c/src/dfm/cleaning/__init__.py">__init__.py</a></td><td>2</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0f5a1b308dbd713a213db413b4b4e430cc75a89c/src/dfm/cleaning/deduper.py">deduper.py</a></td><td>156</td><td>16</td><td>90%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0f5a1b308dbd713a213db413b4b4e430cc75a89c/src/dfm/cleaning/deduper.py#L119-L124">119&ndash;124</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0f5a1b308dbd713a213db413b4b4e430cc75a89c/src/dfm/cleaning/deduper.py#L147">147</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0f5a1b308dbd713a213db413b4b4e430cc75a89c/src/dfm/cleaning/deduper.py#L275">275</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0f5a1b308dbd713a213db413b4b4e430cc75a89c/src/dfm/cleaning/deduper.py#L278">278</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0f5a1b308dbd713a213db413b4b4e430cc75a89c/src/dfm/cleaning/deduper.py#L311">311</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0f5a1b308dbd713a213db413b4b4e430cc75a89c/src/dfm/cleaning/deduper.py#L406">406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0f5a1b308dbd713a213db413b4b4e430cc75a89c/src/dfm/cleaning/deduper.py#L421">421</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0f5a1b308dbd713a213db413b4b4e430cc75a89c/src/dfm/cleaning/deduper.py#L444">444</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0f5a1b308dbd713a213db413b4b4e430cc75a89c/src/dfm/cleaning/deduper.py#L549">549</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0f5a1b308dbd713a213db413b4b4e430cc75a89c/src/dfm/cleaning/deduper.py#L576-L579">576&ndash;579</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0f5a1b308dbd713a213db413b4b4e430cc75a89c/src/dfm/cleaning/deduper_utils.py">deduper_utils.py</a></td><td>26</td><td>3</td><td>88%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0f5a1b308dbd713a213db413b4b4e430cc75a89c/src/dfm/cleaning/deduper_utils.py#L57-L60">57&ndash;60</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0f5a1b308dbd713a213db413b4b4e430cc75a89c/src/dfm/cleaning/quality_filter.py">quality_filter.py</a></td><td>220</td><td>32</td><td>85%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0f5a1b308dbd713a213db413b4b4e430cc75a89c/src/dfm/cleaning/quality_filter.py#L78-L83">78&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0f5a1b308dbd713a213db413b4b4e430cc75a89c/src/dfm/cleaning/quality_filter.py#L264">264</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0f5a1b308dbd713a213db413b4b4e430cc75a89c/src/dfm/cleaning/quality_filter.py#L269">269</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0f5a1b308dbd713a213db413b4b4e430cc75a89c/src/dfm/cleaning/quality_filter.py#L343">343</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0f5a1b308dbd713a213db413b4b4e430cc75a89c/src/dfm/cleaning/quality_filter.py#L352">352</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0f5a1b308dbd713a213db413b4b4e430cc75a89c/src/dfm/cleaning/quality_filter.py#L391-L406">391&ndash;406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0f5a1b308dbd713a213db413b4b4e430cc75a89c/src/dfm/cleaning/quality_filter.py#L539">539</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0f5a1b308dbd713a213db413b4b4e430cc75a89c/src/dfm/cleaning/quality_filter.py#L572-L575">572&ndash;575</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0f5a1b308dbd713a213db413b4b4e430cc75a89c/src/dfm/cleaning/quality_filter.py#L600">600</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0f5a1b308dbd713a213db413b4b4e430cc75a89c/src/dfm/cleaning/quality_filter.py#L632">632</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0f5a1b308dbd713a213db413b4b4e430cc75a89c/src/dfm/cleaning/quality_filter.py#L716">716</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0f5a1b308dbd713a213db413b4b4e430cc75a89c/src/dfm/cleaning/quality_filter.py#L730">730</a></td></tr><tr><td colspan="5"><b>src/dfm/data</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0f5a1b308dbd713a213db413b4b4e430cc75a89c/src/dfm/data/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0f5a1b308dbd713a213db413b4b4e430cc75a89c/src/dfm/data/hate_speech.py">hate_speech.py</a></td><td>11</td><td>11</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0f5a1b308dbd713a213db413b4b4e430cc75a89c/src/dfm/data/hate_speech.py#L1-L20">1&ndash;20</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0f5a1b308dbd713a213db413b4b4e430cc75a89c/src/dfm/data/load.py">load.py</a></td><td>106</td><td>91</td><td>14%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0f5a1b308dbd713a213db413b4b4e430cc75a89c/src/dfm/data/load.py#L35-L50">35&ndash;50</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0f5a1b308dbd713a213db413b4b4e430cc75a89c/src/dfm/data/load.py#L59-L83">59&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0f5a1b308dbd713a213db413b4b4e430cc75a89c/src/dfm/data/load.py#L98-L119">98&ndash;119</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0f5a1b308dbd713a213db413b4b4e430cc75a89c/src/dfm [...]

2022-06-18 08:47 UTC, KennethEnevoldsen commented
<!-- Pytest Coverage Comment: pytest-coverage -->
<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e2a0c58e0abd4edaad1dbdc7e8200bcd4ace20a/README.md"><img alt="Coverage" src="https://img.shields.io/badge/Coverage-60%25-yellow.svg" /></a><br/><details><summary>Coverage Report</summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>src/dfm</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e2a0c58e0abd4edaad1dbdc7e8200bcd4ace20a/src/dfm/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e2a0c58e0abd4edaad1dbdc7e8200bcd4ace20a/src/dfm/train.py">train.py</a></td><td>68</td><td>68</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e2a0c58e0abd4edaad1dbdc7e8200bcd4ace20a/src/dfm/train.py#L14-L226">14&ndash;226</a></td></tr><tr><td colspan="5"><b>src/dfm/cleaning</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e2a0c58e0abd4edaad1dbdc7e8200bcd4ace20a/src/dfm/cleaning/__init__.py">__init__.py</a></td><td>2</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e2a0c58e0abd4edaad1dbdc7e8200bcd4ace20a/src/dfm/cleaning/deduper.py">deduper.py</a></td><td>156</td><td>16</td><td>90%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e2a0c58e0abd4edaad1dbdc7e8200bcd4ace20a/src/dfm/cleaning/deduper.py#L119-L124">119&ndash;124</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e2a0c58e0abd4edaad1dbdc7e8200bcd4ace20a/src/dfm/cleaning/deduper.py#L147">147</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e2a0c58e0abd4edaad1dbdc7e8200bcd4ace20a/src/dfm/cleaning/deduper.py#L275">275</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e2a0c58e0abd4edaad1dbdc7e8200bcd4ace20a/src/dfm/cleaning/deduper.py#L278">278</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e2a0c58e0abd4edaad1dbdc7e8200bcd4ace20a/src/dfm/cleaning/deduper.py#L311">311</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e2a0c58e0abd4edaad1dbdc7e8200bcd4ace20a/src/dfm/cleaning/deduper.py#L406">406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e2a0c58e0abd4edaad1dbdc7e8200bcd4ace20a/src/dfm/cleaning/deduper.py#L421">421</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e2a0c58e0abd4edaad1dbdc7e8200bcd4ace20a/src/dfm/cleaning/deduper.py#L444">444</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e2a0c58e0abd4edaad1dbdc7e8200bcd4ace20a/src/dfm/cleaning/deduper.py#L549">549</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e2a0c58e0abd4edaad1dbdc7e8200bcd4ace20a/src/dfm/cleaning/deduper.py#L576-L579">576&ndash;579</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e2a0c58e0abd4edaad1dbdc7e8200bcd4ace20a/src/dfm/cleaning/deduper_utils.py">deduper_utils.py</a></td><td>26</td><td>3</td><td>88%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e2a0c58e0abd4edaad1dbdc7e8200bcd4ace20a/src/dfm/cleaning/deduper_utils.py#L57-L60">57&ndash;60</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e2a0c58e0abd4edaad1dbdc7e8200bcd4ace20a/src/dfm/cleaning/quality_filter.py">quality_filter.py</a></td><td>220</td><td>32</td><td>85%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e2a0c58e0abd4edaad1dbdc7e8200bcd4ace20a/src/dfm/cleaning/quality_filter.py#L78-L83">78&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e2a0c58e0abd4edaad1dbdc7e8200bcd4ace20a/src/dfm/cleaning/quality_filter.py#L264">264</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e2a0c58e0abd4edaad1dbdc7e8200bcd4ace20a/src/dfm/cleaning/quality_filter.py#L269">269</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e2a0c58e0abd4edaad1dbdc7e8200bcd4ace20a/src/dfm/cleaning/quality_filter.py#L343">343</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e2a0c58e0abd4edaad1dbdc7e8200bcd4ace20a/src/dfm/cleaning/quality_filter.py#L352">352</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e2a0c58e0abd4edaad1dbdc7e8200bcd4ace20a/src/dfm/cleaning/quality_filter.py#L391-L406">391&ndash;406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e2a0c58e0abd4edaad1dbdc7e8200bcd4ace20a/src/dfm/cleaning/quality_filter.py#L539">539</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e2a0c58e0abd4edaad1dbdc7e8200bcd4ace20a/src/dfm/cleaning/quality_filter.py#L572-L575">572&ndash;575</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e2a0c58e0abd4edaad1dbdc7e8200bcd4ace20a/src/dfm/cleaning/quality_filter.py#L600">600</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e2a0c58e0abd4edaad1dbdc7e8200bcd4ace20a/src/dfm/cleaning/quality_filter.py#L632">632</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e2a0c58e0abd4edaad1dbdc7e8200bcd4ace20a/src/dfm/cleaning/quality_filter.py#L716">716</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e2a0c58e0abd4edaad1dbdc7e8200bcd4ace20a/src/dfm/cleaning/quality_filter.py#L730">730</a></td></tr><tr><td colspan="5"><b>src/dfm/data</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e2a0c58e0abd4edaad1dbdc7e8200bcd4ace20a/src/dfm/data/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e2a0c58e0abd4edaad1dbdc7e8200bcd4ace20a/src/dfm/data/hate_speech.py">hate_speech.py</a></td><td>11</td><td>11</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e2a0c58e0abd4edaad1dbdc7e8200bcd4ace20a/src/dfm/data/hate_speech.py#L1-L20">1&ndash;20</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e2a0c58e0abd4edaad1dbdc7e8200bcd4ace20a/src/dfm/data/load.py">load.py</a></td><td>106</td><td>91</td><td>14%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e2a0c58e0abd4edaad1dbdc7e8200bcd4ace20a/src/dfm/data/load.py#L35-L50">35&ndash;50</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e2a0c58e0abd4edaad1dbdc7e8200bcd4ace20a/src/dfm/data/load.py#L59-L83">59&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e2a0c58e0abd4edaad1dbdc7e8200bcd4ace20a/src/dfm/data/load.py#L98-L119">98&ndash;119</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e2a0c58e0abd4edaad1dbdc7e8200bcd4ace20a/src/dfm [...]

2022-06-18 08:47 UTC, KennethEnevoldsen commented
<!-- Pytest Coverage Comment: pytest-coverage -->
<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8299fb83f88b495d339e632f93bb2bc340b37db0/README.md"><img alt="Coverage" src="https://img.shields.io/badge/Coverage-60%25-yellow.svg" /></a><br/><details><summary>Coverage Report</summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>src/dfm</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8299fb83f88b495d339e632f93bb2bc340b37db0/src/dfm/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8299fb83f88b495d339e632f93bb2bc340b37db0/src/dfm/train.py">train.py</a></td><td>68</td><td>68</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8299fb83f88b495d339e632f93bb2bc340b37db0/src/dfm/train.py#L14-L226">14&ndash;226</a></td></tr><tr><td colspan="5"><b>src/dfm/cleaning</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8299fb83f88b495d339e632f93bb2bc340b37db0/src/dfm/cleaning/__init__.py">__init__.py</a></td><td>2</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8299fb83f88b495d339e632f93bb2bc340b37db0/src/dfm/cleaning/deduper.py">deduper.py</a></td><td>156</td><td>16</td><td>90%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8299fb83f88b495d339e632f93bb2bc340b37db0/src/dfm/cleaning/deduper.py#L119-L124">119&ndash;124</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8299fb83f88b495d339e632f93bb2bc340b37db0/src/dfm/cleaning/deduper.py#L147">147</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8299fb83f88b495d339e632f93bb2bc340b37db0/src/dfm/cleaning/deduper.py#L275">275</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8299fb83f88b495d339e632f93bb2bc340b37db0/src/dfm/cleaning/deduper.py#L278">278</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8299fb83f88b495d339e632f93bb2bc340b37db0/src/dfm/cleaning/deduper.py#L311">311</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8299fb83f88b495d339e632f93bb2bc340b37db0/src/dfm/cleaning/deduper.py#L406">406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8299fb83f88b495d339e632f93bb2bc340b37db0/src/dfm/cleaning/deduper.py#L421">421</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8299fb83f88b495d339e632f93bb2bc340b37db0/src/dfm/cleaning/deduper.py#L444">444</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8299fb83f88b495d339e632f93bb2bc340b37db0/src/dfm/cleaning/deduper.py#L549">549</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8299fb83f88b495d339e632f93bb2bc340b37db0/src/dfm/cleaning/deduper.py#L576-L579">576&ndash;579</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8299fb83f88b495d339e632f93bb2bc340b37db0/src/dfm/cleaning/deduper_utils.py">deduper_utils.py</a></td><td>26</td><td>3</td><td>88%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8299fb83f88b495d339e632f93bb2bc340b37db0/src/dfm/cleaning/deduper_utils.py#L57-L60">57&ndash;60</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8299fb83f88b495d339e632f93bb2bc340b37db0/src/dfm/cleaning/quality_filter.py">quality_filter.py</a></td><td>220</td><td>32</td><td>85%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8299fb83f88b495d339e632f93bb2bc340b37db0/src/dfm/cleaning/quality_filter.py#L78-L83">78&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8299fb83f88b495d339e632f93bb2bc340b37db0/src/dfm/cleaning/quality_filter.py#L264">264</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8299fb83f88b495d339e632f93bb2bc340b37db0/src/dfm/cleaning/quality_filter.py#L269">269</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8299fb83f88b495d339e632f93bb2bc340b37db0/src/dfm/cleaning/quality_filter.py#L343">343</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8299fb83f88b495d339e632f93bb2bc340b37db0/src/dfm/cleaning/quality_filter.py#L352">352</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8299fb83f88b495d339e632f93bb2bc340b37db0/src/dfm/cleaning/quality_filter.py#L391-L406">391&ndash;406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8299fb83f88b495d339e632f93bb2bc340b37db0/src/dfm/cleaning/quality_filter.py#L539">539</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8299fb83f88b495d339e632f93bb2bc340b37db0/src/dfm/cleaning/quality_filter.py#L572-L575">572&ndash;575</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8299fb83f88b495d339e632f93bb2bc340b37db0/src/dfm/cleaning/quality_filter.py#L600">600</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8299fb83f88b495d339e632f93bb2bc340b37db0/src/dfm/cleaning/quality_filter.py#L632">632</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8299fb83f88b495d339e632f93bb2bc340b37db0/src/dfm/cleaning/quality_filter.py#L716">716</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8299fb83f88b495d339e632f93bb2bc340b37db0/src/dfm/cleaning/quality_filter.py#L730">730</a></td></tr><tr><td colspan="5"><b>src/dfm/data</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8299fb83f88b495d339e632f93bb2bc340b37db0/src/dfm/data/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8299fb83f88b495d339e632f93bb2bc340b37db0/src/dfm/data/hate_speech.py">hate_speech.py</a></td><td>11</td><td>11</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8299fb83f88b495d339e632f93bb2bc340b37db0/src/dfm/data/hate_speech.py#L1-L20">1&ndash;20</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8299fb83f88b495d339e632f93bb2bc340b37db0/src/dfm/data/load.py">load.py</a></td><td>106</td><td>91</td><td>14%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8299fb83f88b495d339e632f93bb2bc340b37db0/src/dfm/data/load.py#L35-L50">35&ndash;50</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8299fb83f88b495d339e632f93bb2bc340b37db0/src/dfm/data/load.py#L59-L83">59&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8299fb83f88b495d339e632f93bb2bc340b37db0/src/dfm/data/load.py#L98-L119">98&ndash;119</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8299fb83f88b495d339e632f93bb2bc340b37db0/src/dfm [...]

2022-06-18 08:48 UTC, KennethEnevoldsen commented
<!-- Pytest Coverage Comment: pytest-coverage -->
<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0666e0e1cce2bacdf061c9a1ca44a5f9f2bcb561/README.md"><img alt="Coverage" src="https://img.shields.io/badge/Coverage-60%25-yellow.svg" /></a><br/><details><summary>Coverage Report</summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>src/dfm</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0666e0e1cce2bacdf061c9a1ca44a5f9f2bcb561/src/dfm/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0666e0e1cce2bacdf061c9a1ca44a5f9f2bcb561/src/dfm/train.py">train.py</a></td><td>68</td><td>68</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0666e0e1cce2bacdf061c9a1ca44a5f9f2bcb561/src/dfm/train.py#L14-L226">14&ndash;226</a></td></tr><tr><td colspan="5"><b>src/dfm/cleaning</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0666e0e1cce2bacdf061c9a1ca44a5f9f2bcb561/src/dfm/cleaning/__init__.py">__init__.py</a></td><td>2</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0666e0e1cce2bacdf061c9a1ca44a5f9f2bcb561/src/dfm/cleaning/deduper.py">deduper.py</a></td><td>156</td><td>16</td><td>90%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0666e0e1cce2bacdf061c9a1ca44a5f9f2bcb561/src/dfm/cleaning/deduper.py#L119-L124">119&ndash;124</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0666e0e1cce2bacdf061c9a1ca44a5f9f2bcb561/src/dfm/cleaning/deduper.py#L147">147</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0666e0e1cce2bacdf061c9a1ca44a5f9f2bcb561/src/dfm/cleaning/deduper.py#L275">275</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0666e0e1cce2bacdf061c9a1ca44a5f9f2bcb561/src/dfm/cleaning/deduper.py#L278">278</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0666e0e1cce2bacdf061c9a1ca44a5f9f2bcb561/src/dfm/cleaning/deduper.py#L311">311</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0666e0e1cce2bacdf061c9a1ca44a5f9f2bcb561/src/dfm/cleaning/deduper.py#L406">406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0666e0e1cce2bacdf061c9a1ca44a5f9f2bcb561/src/dfm/cleaning/deduper.py#L421">421</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0666e0e1cce2bacdf061c9a1ca44a5f9f2bcb561/src/dfm/cleaning/deduper.py#L444">444</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0666e0e1cce2bacdf061c9a1ca44a5f9f2bcb561/src/dfm/cleaning/deduper.py#L549">549</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0666e0e1cce2bacdf061c9a1ca44a5f9f2bcb561/src/dfm/cleaning/deduper.py#L576-L579">576&ndash;579</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0666e0e1cce2bacdf061c9a1ca44a5f9f2bcb561/src/dfm/cleaning/deduper_utils.py">deduper_utils.py</a></td><td>26</td><td>3</td><td>88%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0666e0e1cce2bacdf061c9a1ca44a5f9f2bcb561/src/dfm/cleaning/deduper_utils.py#L57-L60">57&ndash;60</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0666e0e1cce2bacdf061c9a1ca44a5f9f2bcb561/src/dfm/cleaning/quality_filter.py">quality_filter.py</a></td><td>220</td><td>32</td><td>85%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0666e0e1cce2bacdf061c9a1ca44a5f9f2bcb561/src/dfm/cleaning/quality_filter.py#L78-L83">78&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0666e0e1cce2bacdf061c9a1ca44a5f9f2bcb561/src/dfm/cleaning/quality_filter.py#L264">264</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0666e0e1cce2bacdf061c9a1ca44a5f9f2bcb561/src/dfm/cleaning/quality_filter.py#L269">269</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0666e0e1cce2bacdf061c9a1ca44a5f9f2bcb561/src/dfm/cleaning/quality_filter.py#L343">343</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0666e0e1cce2bacdf061c9a1ca44a5f9f2bcb561/src/dfm/cleaning/quality_filter.py#L352">352</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0666e0e1cce2bacdf061c9a1ca44a5f9f2bcb561/src/dfm/cleaning/quality_filter.py#L391-L406">391&ndash;406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0666e0e1cce2bacdf061c9a1ca44a5f9f2bcb561/src/dfm/cleaning/quality_filter.py#L539">539</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0666e0e1cce2bacdf061c9a1ca44a5f9f2bcb561/src/dfm/cleaning/quality_filter.py#L572-L575">572&ndash;575</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0666e0e1cce2bacdf061c9a1ca44a5f9f2bcb561/src/dfm/cleaning/quality_filter.py#L600">600</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0666e0e1cce2bacdf061c9a1ca44a5f9f2bcb561/src/dfm/cleaning/quality_filter.py#L632">632</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0666e0e1cce2bacdf061c9a1ca44a5f9f2bcb561/src/dfm/cleaning/quality_filter.py#L716">716</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0666e0e1cce2bacdf061c9a1ca44a5f9f2bcb561/src/dfm/cleaning/quality_filter.py#L730">730</a></td></tr><tr><td colspan="5"><b>src/dfm/data</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0666e0e1cce2bacdf061c9a1ca44a5f9f2bcb561/src/dfm/data/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0666e0e1cce2bacdf061c9a1ca44a5f9f2bcb561/src/dfm/data/hate_speech.py">hate_speech.py</a></td><td>11</td><td>11</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0666e0e1cce2bacdf061c9a1ca44a5f9f2bcb561/src/dfm/data/hate_speech.py#L1-L20">1&ndash;20</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0666e0e1cce2bacdf061c9a1ca44a5f9f2bcb561/src/dfm/data/load.py">load.py</a></td><td>106</td><td>91</td><td>14%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0666e0e1cce2bacdf061c9a1ca44a5f9f2bcb561/src/dfm/data/load.py#L35-L50">35&ndash;50</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0666e0e1cce2bacdf061c9a1ca44a5f9f2bcb561/src/dfm/data/load.py#L59-L83">59&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0666e0e1cce2bacdf061c9a1ca44a5f9f2bcb561/src/dfm/data/load.py#L98-L119">98&ndash;119</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0666e0e1cce2bacdf061c9a1ca44a5f9f2bcb561/src/dfm [...]

2022-06-18 08:49 UTC, KennethEnevoldsen commented
<!-- Pytest Coverage Comment: pytest-coverage -->
<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/410c2dd6f075f60189ee047a33f4090feb0263c9/README.md"><img alt="Coverage" src="https://img.shields.io/badge/Coverage-60%25-yellow.svg" /></a><br/><details><summary>Coverage Report</summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>src/dfm</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/410c2dd6f075f60189ee047a33f4090feb0263c9/src/dfm/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/410c2dd6f075f60189ee047a33f4090feb0263c9/src/dfm/train.py">train.py</a></td><td>68</td><td>68</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/410c2dd6f075f60189ee047a33f4090feb0263c9/src/dfm/train.py#L14-L226">14&ndash;226</a></td></tr><tr><td colspan="5"><b>src/dfm/cleaning</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/410c2dd6f075f60189ee047a33f4090feb0263c9/src/dfm/cleaning/__init__.py">__init__.py</a></td><td>2</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/410c2dd6f075f60189ee047a33f4090feb0263c9/src/dfm/cleaning/deduper.py">deduper.py</a></td><td>156</td><td>16</td><td>90%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/410c2dd6f075f60189ee047a33f4090feb0263c9/src/dfm/cleaning/deduper.py#L119-L124">119&ndash;124</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/410c2dd6f075f60189ee047a33f4090feb0263c9/src/dfm/cleaning/deduper.py#L147">147</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/410c2dd6f075f60189ee047a33f4090feb0263c9/src/dfm/cleaning/deduper.py#L275">275</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/410c2dd6f075f60189ee047a33f4090feb0263c9/src/dfm/cleaning/deduper.py#L278">278</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/410c2dd6f075f60189ee047a33f4090feb0263c9/src/dfm/cleaning/deduper.py#L311">311</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/410c2dd6f075f60189ee047a33f4090feb0263c9/src/dfm/cleaning/deduper.py#L406">406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/410c2dd6f075f60189ee047a33f4090feb0263c9/src/dfm/cleaning/deduper.py#L421">421</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/410c2dd6f075f60189ee047a33f4090feb0263c9/src/dfm/cleaning/deduper.py#L444">444</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/410c2dd6f075f60189ee047a33f4090feb0263c9/src/dfm/cleaning/deduper.py#L549">549</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/410c2dd6f075f60189ee047a33f4090feb0263c9/src/dfm/cleaning/deduper.py#L576-L579">576&ndash;579</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/410c2dd6f075f60189ee047a33f4090feb0263c9/src/dfm/cleaning/deduper_utils.py">deduper_utils.py</a></td><td>26</td><td>3</td><td>88%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/410c2dd6f075f60189ee047a33f4090feb0263c9/src/dfm/cleaning/deduper_utils.py#L57-L60">57&ndash;60</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/410c2dd6f075f60189ee047a33f4090feb0263c9/src/dfm/cleaning/quality_filter.py">quality_filter.py</a></td><td>220</td><td>32</td><td>85%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/410c2dd6f075f60189ee047a33f4090feb0263c9/src/dfm/cleaning/quality_filter.py#L78-L83">78&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/410c2dd6f075f60189ee047a33f4090feb0263c9/src/dfm/cleaning/quality_filter.py#L264">264</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/410c2dd6f075f60189ee047a33f4090feb0263c9/src/dfm/cleaning/quality_filter.py#L269">269</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/410c2dd6f075f60189ee047a33f4090feb0263c9/src/dfm/cleaning/quality_filter.py#L343">343</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/410c2dd6f075f60189ee047a33f4090feb0263c9/src/dfm/cleaning/quality_filter.py#L352">352</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/410c2dd6f075f60189ee047a33f4090feb0263c9/src/dfm/cleaning/quality_filter.py#L391-L406">391&ndash;406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/410c2dd6f075f60189ee047a33f4090feb0263c9/src/dfm/cleaning/quality_filter.py#L539">539</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/410c2dd6f075f60189ee047a33f4090feb0263c9/src/dfm/cleaning/quality_filter.py#L572-L575">572&ndash;575</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/410c2dd6f075f60189ee047a33f4090feb0263c9/src/dfm/cleaning/quality_filter.py#L600">600</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/410c2dd6f075f60189ee047a33f4090feb0263c9/src/dfm/cleaning/quality_filter.py#L632">632</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/410c2dd6f075f60189ee047a33f4090feb0263c9/src/dfm/cleaning/quality_filter.py#L716">716</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/410c2dd6f075f60189ee047a33f4090feb0263c9/src/dfm/cleaning/quality_filter.py#L730">730</a></td></tr><tr><td colspan="5"><b>src/dfm/data</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/410c2dd6f075f60189ee047a33f4090feb0263c9/src/dfm/data/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/410c2dd6f075f60189ee047a33f4090feb0263c9/src/dfm/data/hate_speech.py">hate_speech.py</a></td><td>11</td><td>11</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/410c2dd6f075f60189ee047a33f4090feb0263c9/src/dfm/data/hate_speech.py#L1-L20">1&ndash;20</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/410c2dd6f075f60189ee047a33f4090feb0263c9/src/dfm/data/load.py">load.py</a></td><td>106</td><td>91</td><td>14%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/410c2dd6f075f60189ee047a33f4090feb0263c9/src/dfm/data/load.py#L35-L50">35&ndash;50</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/410c2dd6f075f60189ee047a33f4090feb0263c9/src/dfm/data/load.py#L59-L83">59&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/410c2dd6f075f60189ee047a33f4090feb0263c9/src/dfm/data/load.py#L98-L119">98&ndash;119</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/410c2dd6f075f60189ee047a33f4090feb0263c9/src/dfm [...]

2022-06-18 08:52 UTC, KennethEnevoldsen commented on docs/datasheets/Netarkivet_text.md
> +The sites which passed the quality filter were deduplicated pr. year consist of 865 billion tokens of which 134 (0.16%) billion were left after filtering and deduplication.
This should clarify it. It is the whole dataset. adn 134 after filtering.

2022-06-18 08:52 UTC, KennethEnevoldsen commented
<!-- Pytest Coverage Comment: pytest-coverage -->
<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/216a974588db9f8c817a98708f97f9c876d0182e/README.md"><img alt="Coverage" src="https://img.shields.io/badge/Coverage-60%25-yellow.svg" /></a><br/><details><summary>Coverage Report</summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>src/dfm</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/216a974588db9f8c817a98708f97f9c876d0182e/src/dfm/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/216a974588db9f8c817a98708f97f9c876d0182e/src/dfm/train.py">train.py</a></td><td>68</td><td>68</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/216a974588db9f8c817a98708f97f9c876d0182e/src/dfm/train.py#L14-L226">14&ndash;226</a></td></tr><tr><td colspan="5"><b>src/dfm/cleaning</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/216a974588db9f8c817a98708f97f9c876d0182e/src/dfm/cleaning/__init__.py">__init__.py</a></td><td>2</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/216a974588db9f8c817a98708f97f9c876d0182e/src/dfm/cleaning/deduper.py">deduper.py</a></td><td>156</td><td>16</td><td>90%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/216a974588db9f8c817a98708f97f9c876d0182e/src/dfm/cleaning/deduper.py#L119-L124">119&ndash;124</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/216a974588db9f8c817a98708f97f9c876d0182e/src/dfm/cleaning/deduper.py#L147">147</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/216a974588db9f8c817a98708f97f9c876d0182e/src/dfm/cleaning/deduper.py#L275">275</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/216a974588db9f8c817a98708f97f9c876d0182e/src/dfm/cleaning/deduper.py#L278">278</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/216a974588db9f8c817a98708f97f9c876d0182e/src/dfm/cleaning/deduper.py#L311">311</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/216a974588db9f8c817a98708f97f9c876d0182e/src/dfm/cleaning/deduper.py#L406">406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/216a974588db9f8c817a98708f97f9c876d0182e/src/dfm/cleaning/deduper.py#L421">421</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/216a974588db9f8c817a98708f97f9c876d0182e/src/dfm/cleaning/deduper.py#L444">444</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/216a974588db9f8c817a98708f97f9c876d0182e/src/dfm/cleaning/deduper.py#L549">549</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/216a974588db9f8c817a98708f97f9c876d0182e/src/dfm/cleaning/deduper.py#L576-L579">576&ndash;579</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/216a974588db9f8c817a98708f97f9c876d0182e/src/dfm/cleaning/deduper_utils.py">deduper_utils.py</a></td><td>26</td><td>3</td><td>88%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/216a974588db9f8c817a98708f97f9c876d0182e/src/dfm/cleaning/deduper_utils.py#L57-L60">57&ndash;60</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/216a974588db9f8c817a98708f97f9c876d0182e/src/dfm/cleaning/quality_filter.py">quality_filter.py</a></td><td>220</td><td>32</td><td>85%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/216a974588db9f8c817a98708f97f9c876d0182e/src/dfm/cleaning/quality_filter.py#L78-L83">78&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/216a974588db9f8c817a98708f97f9c876d0182e/src/dfm/cleaning/quality_filter.py#L264">264</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/216a974588db9f8c817a98708f97f9c876d0182e/src/dfm/cleaning/quality_filter.py#L269">269</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/216a974588db9f8c817a98708f97f9c876d0182e/src/dfm/cleaning/quality_filter.py#L343">343</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/216a974588db9f8c817a98708f97f9c876d0182e/src/dfm/cleaning/quality_filter.py#L352">352</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/216a974588db9f8c817a98708f97f9c876d0182e/src/dfm/cleaning/quality_filter.py#L391-L406">391&ndash;406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/216a974588db9f8c817a98708f97f9c876d0182e/src/dfm/cleaning/quality_filter.py#L539">539</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/216a974588db9f8c817a98708f97f9c876d0182e/src/dfm/cleaning/quality_filter.py#L572-L575">572&ndash;575</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/216a974588db9f8c817a98708f97f9c876d0182e/src/dfm/cleaning/quality_filter.py#L600">600</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/216a974588db9f8c817a98708f97f9c876d0182e/src/dfm/cleaning/quality_filter.py#L632">632</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/216a974588db9f8c817a98708f97f9c876d0182e/src/dfm/cleaning/quality_filter.py#L716">716</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/216a974588db9f8c817a98708f97f9c876d0182e/src/dfm/cleaning/quality_filter.py#L730">730</a></td></tr><tr><td colspan="5"><b>src/dfm/data</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/216a974588db9f8c817a98708f97f9c876d0182e/src/dfm/data/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/216a974588db9f8c817a98708f97f9c876d0182e/src/dfm/data/hate_speech.py">hate_speech.py</a></td><td>11</td><td>11</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/216a974588db9f8c817a98708f97f9c876d0182e/src/dfm/data/hate_speech.py#L1-L20">1&ndash;20</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/216a974588db9f8c817a98708f97f9c876d0182e/src/dfm/data/load.py">load.py</a></td><td>106</td><td>91</td><td>14%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/216a974588db9f8c817a98708f97f9c876d0182e/src/dfm/data/load.py#L35-L50">35&ndash;50</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/216a974588db9f8c817a98708f97f9c876d0182e/src/dfm/data/load.py#L59-L83">59&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/216a974588db9f8c817a98708f97f9c876d0182e/src/dfm/data/load.py#L98-L119">98&ndash;119</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/216a974588db9f8c817a98708f97f9c876d0182e/src/dfm [...]

2022-06-18 08:59 UTC, KennethEnevoldsen commented
<!-- Pytest Coverage Comment: pytest-coverage -->
<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/df46f67756d62203387328d023c1695d888e5b90/README.md"><img alt="Coverage" src="https://img.shields.io/badge/Coverage-60%25-yellow.svg" /></a><br/><details><summary>Coverage Report</summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>src/dfm</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/df46f67756d62203387328d023c1695d888e5b90/src/dfm/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/df46f67756d62203387328d023c1695d888e5b90/src/dfm/train.py">train.py</a></td><td>68</td><td>68</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/df46f67756d62203387328d023c1695d888e5b90/src/dfm/train.py#L14-L226">14&ndash;226</a></td></tr><tr><td colspan="5"><b>src/dfm/cleaning</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/df46f67756d62203387328d023c1695d888e5b90/src/dfm/cleaning/__init__.py">__init__.py</a></td><td>2</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/df46f67756d62203387328d023c1695d888e5b90/src/dfm/cleaning/deduper.py">deduper.py</a></td><td>156</td><td>16</td><td>90%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/df46f67756d62203387328d023c1695d888e5b90/src/dfm/cleaning/deduper.py#L119-L124">119&ndash;124</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/df46f67756d62203387328d023c1695d888e5b90/src/dfm/cleaning/deduper.py#L147">147</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/df46f67756d62203387328d023c1695d888e5b90/src/dfm/cleaning/deduper.py#L275">275</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/df46f67756d62203387328d023c1695d888e5b90/src/dfm/cleaning/deduper.py#L278">278</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/df46f67756d62203387328d023c1695d888e5b90/src/dfm/cleaning/deduper.py#L311">311</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/df46f67756d62203387328d023c1695d888e5b90/src/dfm/cleaning/deduper.py#L406">406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/df46f67756d62203387328d023c1695d888e5b90/src/dfm/cleaning/deduper.py#L421">421</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/df46f67756d62203387328d023c1695d888e5b90/src/dfm/cleaning/deduper.py#L444">444</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/df46f67756d62203387328d023c1695d888e5b90/src/dfm/cleaning/deduper.py#L549">549</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/df46f67756d62203387328d023c1695d888e5b90/src/dfm/cleaning/deduper.py#L576-L579">576&ndash;579</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/df46f67756d62203387328d023c1695d888e5b90/src/dfm/cleaning/deduper_utils.py">deduper_utils.py</a></td><td>26</td><td>3</td><td>88%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/df46f67756d62203387328d023c1695d888e5b90/src/dfm/cleaning/deduper_utils.py#L57-L60">57&ndash;60</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/df46f67756d62203387328d023c1695d888e5b90/src/dfm/cleaning/quality_filter.py">quality_filter.py</a></td><td>220</td><td>32</td><td>85%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/df46f67756d62203387328d023c1695d888e5b90/src/dfm/cleaning/quality_filter.py#L78-L83">78&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/df46f67756d62203387328d023c1695d888e5b90/src/dfm/cleaning/quality_filter.py#L264">264</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/df46f67756d62203387328d023c1695d888e5b90/src/dfm/cleaning/quality_filter.py#L269">269</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/df46f67756d62203387328d023c1695d888e5b90/src/dfm/cleaning/quality_filter.py#L343">343</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/df46f67756d62203387328d023c1695d888e5b90/src/dfm/cleaning/quality_filter.py#L352">352</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/df46f67756d62203387328d023c1695d888e5b90/src/dfm/cleaning/quality_filter.py#L391-L406">391&ndash;406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/df46f67756d62203387328d023c1695d888e5b90/src/dfm/cleaning/quality_filter.py#L539">539</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/df46f67756d62203387328d023c1695d888e5b90/src/dfm/cleaning/quality_filter.py#L572-L575">572&ndash;575</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/df46f67756d62203387328d023c1695d888e5b90/src/dfm/cleaning/quality_filter.py#L600">600</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/df46f67756d62203387328d023c1695d888e5b90/src/dfm/cleaning/quality_filter.py#L632">632</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/df46f67756d62203387328d023c1695d888e5b90/src/dfm/cleaning/quality_filter.py#L716">716</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/df46f67756d62203387328d023c1695d888e5b90/src/dfm/cleaning/quality_filter.py#L730">730</a></td></tr><tr><td colspan="5"><b>src/dfm/data</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/df46f67756d62203387328d023c1695d888e5b90/src/dfm/data/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/df46f67756d62203387328d023c1695d888e5b90/src/dfm/data/hate_speech.py">hate_speech.py</a></td><td>11</td><td>11</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/df46f67756d62203387328d023c1695d888e5b90/src/dfm/data/hate_speech.py#L1-L20">1&ndash;20</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/df46f67756d62203387328d023c1695d888e5b90/src/dfm/data/load.py">load.py</a></td><td>106</td><td>91</td><td>14%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/df46f67756d62203387328d023c1695d888e5b90/src/dfm/data/load.py#L35-L50">35&ndash;50</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/df46f67756d62203387328d023c1695d888e5b90/src/dfm/data/load.py#L59-L83">59&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/df46f67756d62203387328d023c1695d888e5b90/src/dfm/data/load.py#L98-L119">98&ndash;119</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/df46f67756d62203387328d023c1695d888e5b90/src/dfm [...]

2022-06-18 09:16 UTC, KennethEnevoldsen commented on docs/datasheets/Netarkivet_text.md
> +| 9   | domain_key  | object |
Hopefully this is now better?

2022-06-18 09:18 UTC, KennethEnevoldsen commented on docs/datasheets/Netarkivet_text.md
> +- Event collections of two-three event yearly (e.g. elections and the corona pandemic)
2-3 event pr. year. Hopefully it is more clear now?

2022-06-18 09:22 UTC, KennethEnevoldsen commented
<!-- Pytest Coverage Comment: pytest-coverage -->
<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/65d42283347a6d67c7ab053d6b663cdeaf761f99/README.md"><img alt="Coverage" src="https://img.shields.io/badge/Coverage-60%25-yellow.svg" /></a><br/><details><summary>Coverage Report</summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>src/dfm</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/65d42283347a6d67c7ab053d6b663cdeaf761f99/src/dfm/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/65d42283347a6d67c7ab053d6b663cdeaf761f99/src/dfm/train.py">train.py</a></td><td>68</td><td>68</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/65d42283347a6d67c7ab053d6b663cdeaf761f99/src/dfm/train.py#L14-L226">14&ndash;226</a></td></tr><tr><td colspan="5"><b>src/dfm/cleaning</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/65d42283347a6d67c7ab053d6b663cdeaf761f99/src/dfm/cleaning/__init__.py">__init__.py</a></td><td>2</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/65d42283347a6d67c7ab053d6b663cdeaf761f99/src/dfm/cleaning/deduper.py">deduper.py</a></td><td>156</td><td>16</td><td>90%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/65d42283347a6d67c7ab053d6b663cdeaf761f99/src/dfm/cleaning/deduper.py#L119-L124">119&ndash;124</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/65d42283347a6d67c7ab053d6b663cdeaf761f99/src/dfm/cleaning/deduper.py#L147">147</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/65d42283347a6d67c7ab053d6b663cdeaf761f99/src/dfm/cleaning/deduper.py#L275">275</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/65d42283347a6d67c7ab053d6b663cdeaf761f99/src/dfm/cleaning/deduper.py#L278">278</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/65d42283347a6d67c7ab053d6b663cdeaf761f99/src/dfm/cleaning/deduper.py#L311">311</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/65d42283347a6d67c7ab053d6b663cdeaf761f99/src/dfm/cleaning/deduper.py#L406">406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/65d42283347a6d67c7ab053d6b663cdeaf761f99/src/dfm/cleaning/deduper.py#L421">421</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/65d42283347a6d67c7ab053d6b663cdeaf761f99/src/dfm/cleaning/deduper.py#L444">444</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/65d42283347a6d67c7ab053d6b663cdeaf761f99/src/dfm/cleaning/deduper.py#L549">549</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/65d42283347a6d67c7ab053d6b663cdeaf761f99/src/dfm/cleaning/deduper.py#L576-L579">576&ndash;579</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/65d42283347a6d67c7ab053d6b663cdeaf761f99/src/dfm/cleaning/deduper_utils.py">deduper_utils.py</a></td><td>26</td><td>3</td><td>88%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/65d42283347a6d67c7ab053d6b663cdeaf761f99/src/dfm/cleaning/deduper_utils.py#L57-L60">57&ndash;60</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/65d42283347a6d67c7ab053d6b663cdeaf761f99/src/dfm/cleaning/quality_filter.py">quality_filter.py</a></td><td>220</td><td>32</td><td>85%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/65d42283347a6d67c7ab053d6b663cdeaf761f99/src/dfm/cleaning/quality_filter.py#L78-L83">78&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/65d42283347a6d67c7ab053d6b663cdeaf761f99/src/dfm/cleaning/quality_filter.py#L264">264</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/65d42283347a6d67c7ab053d6b663cdeaf761f99/src/dfm/cleaning/quality_filter.py#L269">269</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/65d42283347a6d67c7ab053d6b663cdeaf761f99/src/dfm/cleaning/quality_filter.py#L343">343</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/65d42283347a6d67c7ab053d6b663cdeaf761f99/src/dfm/cleaning/quality_filter.py#L352">352</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/65d42283347a6d67c7ab053d6b663cdeaf761f99/src/dfm/cleaning/quality_filter.py#L391-L406">391&ndash;406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/65d42283347a6d67c7ab053d6b663cdeaf761f99/src/dfm/cleaning/quality_filter.py#L539">539</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/65d42283347a6d67c7ab053d6b663cdeaf761f99/src/dfm/cleaning/quality_filter.py#L572-L575">572&ndash;575</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/65d42283347a6d67c7ab053d6b663cdeaf761f99/src/dfm/cleaning/quality_filter.py#L600">600</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/65d42283347a6d67c7ab053d6b663cdeaf761f99/src/dfm/cleaning/quality_filter.py#L632">632</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/65d42283347a6d67c7ab053d6b663cdeaf761f99/src/dfm/cleaning/quality_filter.py#L716">716</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/65d42283347a6d67c7ab053d6b663cdeaf761f99/src/dfm/cleaning/quality_filter.py#L730">730</a></td></tr><tr><td colspan="5"><b>src/dfm/data</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/65d42283347a6d67c7ab053d6b663cdeaf761f99/src/dfm/data/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/65d42283347a6d67c7ab053d6b663cdeaf761f99/src/dfm/data/hate_speech.py">hate_speech.py</a></td><td>11</td><td>11</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/65d42283347a6d67c7ab053d6b663cdeaf761f99/src/dfm/data/hate_speech.py#L1-L20">1&ndash;20</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/65d42283347a6d67c7ab053d6b663cdeaf761f99/src/dfm/data/load.py">load.py</a></td><td>106</td><td>91</td><td>14%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/65d42283347a6d67c7ab053d6b663cdeaf761f99/src/dfm/data/load.py#L35-L50">35&ndash;50</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/65d42283347a6d67c7ab053d6b663cdeaf761f99/src/dfm/data/load.py#L59-L83">59&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/65d42283347a6d67c7ab053d6b663cdeaf761f99/src/dfm/data/load.py#L98-L119">98&ndash;119</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/65d42283347a6d67c7ab053d6b663cdeaf761f99/src/dfm [...]

2022-06-18 10:41 UTC, saattrupdan requested changes

2022-06-18 10:41 UTC, saattrupdan commented on docs/datasheets/Netarkivet_text.md
> +`mime_*` indicated The [mime/media type](https://en.wikipedia.org/wiki/Media_type).
```suggestion
`mime_*` indicates the [mime/media type](https://en.wikipedia.org/wiki/Media_type).
```

2022-06-18 10:41 UTC, saattrupdan commented on docs/datasheets/Netarkivet_text.md
> +consist of jobs each with their associated `job-id`.
```suggestion
consists of jobs, each with their associated `job-id`. 
```

2022-06-18 10:41 UTC, saattrupdan commented on docs/datasheets/Netarkivet_text.md
> +Language is the language classified using a the following language detection [library](https://github.com/optimaize/language-detector). `uri` is the URI of the site e.g. `"http://www.apple.com/podcas
```suggestion
Language is the language classified using the following language detection [library](https://github.com/optimaize/language-detector). `uri` is the URI of the site e.g. `"http://www.apple.com/podcasting"`. 
```

2022-06-18 10:41 UTC, saattrupdan commented on docs/datasheets/Netarkivet_text.md
> +`mime_served` could e.g. be `"text/html; charset=iso-8859-1"` and `mime_droid` could e.g. be `"text/html; version=2.0"` and is the mime type identified by the server and by [DROID](https://github.com
```suggestion
`mime_served` could for instance be `"text/html; charset=iso-8859-1"` and `mime_droid` could be `"text/html; version=2.0"` and is the mime type identified by the server and by [DROID](https://github.com/digital-preservation/droid), respectively.
```

2022-06-18 10:41 UTC, saattrupdan commented on docs/datasheets/Netarkivet_text.md
> +A selective subset of Netarkivet is then extracted pr. year from 2006 to 2016 such that
```suggestion
A selective subset of Netarkivet is then extracted per year from 2006 to 2016 such that 
```

2022-06-21 10:11 UTC, KennethEnevoldsen commented
<!-- Pytest Coverage Comment: pytest-coverage -->
<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0a3c9464929ce3036563cb2bbb35b3b93385cfd1/README.md"><img alt="Coverage" src="https://img.shields.io/badge/Coverage-60%25-yellow.svg" /></a><br/><details><summary>Coverage Report</summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>src/dfm</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0a3c9464929ce3036563cb2bbb35b3b93385cfd1/src/dfm/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0a3c9464929ce3036563cb2bbb35b3b93385cfd1/src/dfm/train.py">train.py</a></td><td>68</td><td>68</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0a3c9464929ce3036563cb2bbb35b3b93385cfd1/src/dfm/train.py#L14-L226">14&ndash;226</a></td></tr><tr><td colspan="5"><b>src/dfm/cleaning</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0a3c9464929ce3036563cb2bbb35b3b93385cfd1/src/dfm/cleaning/__init__.py">__init__.py</a></td><td>2</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0a3c9464929ce3036563cb2bbb35b3b93385cfd1/src/dfm/cleaning/deduper.py">deduper.py</a></td><td>156</td><td>16</td><td>90%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0a3c9464929ce3036563cb2bbb35b3b93385cfd1/src/dfm/cleaning/deduper.py#L119-L124">119&ndash;124</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0a3c9464929ce3036563cb2bbb35b3b93385cfd1/src/dfm/cleaning/deduper.py#L147">147</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0a3c9464929ce3036563cb2bbb35b3b93385cfd1/src/dfm/cleaning/deduper.py#L275">275</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0a3c9464929ce3036563cb2bbb35b3b93385cfd1/src/dfm/cleaning/deduper.py#L278">278</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0a3c9464929ce3036563cb2bbb35b3b93385cfd1/src/dfm/cleaning/deduper.py#L311">311</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0a3c9464929ce3036563cb2bbb35b3b93385cfd1/src/dfm/cleaning/deduper.py#L406">406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0a3c9464929ce3036563cb2bbb35b3b93385cfd1/src/dfm/cleaning/deduper.py#L421">421</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0a3c9464929ce3036563cb2bbb35b3b93385cfd1/src/dfm/cleaning/deduper.py#L444">444</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0a3c9464929ce3036563cb2bbb35b3b93385cfd1/src/dfm/cleaning/deduper.py#L549">549</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0a3c9464929ce3036563cb2bbb35b3b93385cfd1/src/dfm/cleaning/deduper.py#L576-L579">576&ndash;579</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0a3c9464929ce3036563cb2bbb35b3b93385cfd1/src/dfm/cleaning/deduper_utils.py">deduper_utils.py</a></td><td>26</td><td>3</td><td>88%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0a3c9464929ce3036563cb2bbb35b3b93385cfd1/src/dfm/cleaning/deduper_utils.py#L57-L60">57&ndash;60</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0a3c9464929ce3036563cb2bbb35b3b93385cfd1/src/dfm/cleaning/quality_filter.py">quality_filter.py</a></td><td>220</td><td>32</td><td>85%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0a3c9464929ce3036563cb2bbb35b3b93385cfd1/src/dfm/cleaning/quality_filter.py#L78-L83">78&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0a3c9464929ce3036563cb2bbb35b3b93385cfd1/src/dfm/cleaning/quality_filter.py#L264">264</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0a3c9464929ce3036563cb2bbb35b3b93385cfd1/src/dfm/cleaning/quality_filter.py#L269">269</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0a3c9464929ce3036563cb2bbb35b3b93385cfd1/src/dfm/cleaning/quality_filter.py#L343">343</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0a3c9464929ce3036563cb2bbb35b3b93385cfd1/src/dfm/cleaning/quality_filter.py#L352">352</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0a3c9464929ce3036563cb2bbb35b3b93385cfd1/src/dfm/cleaning/quality_filter.py#L391-L406">391&ndash;406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0a3c9464929ce3036563cb2bbb35b3b93385cfd1/src/dfm/cleaning/quality_filter.py#L539">539</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0a3c9464929ce3036563cb2bbb35b3b93385cfd1/src/dfm/cleaning/quality_filter.py#L572-L575">572&ndash;575</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0a3c9464929ce3036563cb2bbb35b3b93385cfd1/src/dfm/cleaning/quality_filter.py#L600">600</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0a3c9464929ce3036563cb2bbb35b3b93385cfd1/src/dfm/cleaning/quality_filter.py#L632">632</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0a3c9464929ce3036563cb2bbb35b3b93385cfd1/src/dfm/cleaning/quality_filter.py#L716">716</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0a3c9464929ce3036563cb2bbb35b3b93385cfd1/src/dfm/cleaning/quality_filter.py#L730">730</a></td></tr><tr><td colspan="5"><b>src/dfm/data</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0a3c9464929ce3036563cb2bbb35b3b93385cfd1/src/dfm/data/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0a3c9464929ce3036563cb2bbb35b3b93385cfd1/src/dfm/data/hate_speech.py">hate_speech.py</a></td><td>11</td><td>11</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0a3c9464929ce3036563cb2bbb35b3b93385cfd1/src/dfm/data/hate_speech.py#L1-L20">1&ndash;20</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0a3c9464929ce3036563cb2bbb35b3b93385cfd1/src/dfm/data/load.py">load.py</a></td><td>106</td><td>91</td><td>14%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0a3c9464929ce3036563cb2bbb35b3b93385cfd1/src/dfm/data/load.py#L35-L50">35&ndash;50</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0a3c9464929ce3036563cb2bbb35b3b93385cfd1/src/dfm/data/load.py#L59-L83">59&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0a3c9464929ce3036563cb2bbb35b3b93385cfd1/src/dfm/data/load.py#L98-L119">98&ndash;119</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0a3c9464929ce3036563cb2bbb35b3b93385cfd1/src/dfm [...]

2022-06-21 10:18 UTC, KennethEnevoldsen commented
<!-- Pytest Coverage Comment: pytest-coverage -->
<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/828da9083440ec5d5c154b6a7a6bafd0f025b84b/README.md"><img alt="Coverage" src="https://img.shields.io/badge/Coverage-60%25-yellow.svg" /></a><br/><details><summary>Coverage Report</summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>src/dfm</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/828da9083440ec5d5c154b6a7a6bafd0f025b84b/src/dfm/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/828da9083440ec5d5c154b6a7a6bafd0f025b84b/src/dfm/train.py">train.py</a></td><td>68</td><td>68</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/828da9083440ec5d5c154b6a7a6bafd0f025b84b/src/dfm/train.py#L14-L226">14&ndash;226</a></td></tr><tr><td colspan="5"><b>src/dfm/cleaning</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/828da9083440ec5d5c154b6a7a6bafd0f025b84b/src/dfm/cleaning/__init__.py">__init__.py</a></td><td>2</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/828da9083440ec5d5c154b6a7a6bafd0f025b84b/src/dfm/cleaning/deduper.py">deduper.py</a></td><td>156</td><td>16</td><td>90%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/828da9083440ec5d5c154b6a7a6bafd0f025b84b/src/dfm/cleaning/deduper.py#L119-L124">119&ndash;124</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/828da9083440ec5d5c154b6a7a6bafd0f025b84b/src/dfm/cleaning/deduper.py#L147">147</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/828da9083440ec5d5c154b6a7a6bafd0f025b84b/src/dfm/cleaning/deduper.py#L275">275</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/828da9083440ec5d5c154b6a7a6bafd0f025b84b/src/dfm/cleaning/deduper.py#L278">278</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/828da9083440ec5d5c154b6a7a6bafd0f025b84b/src/dfm/cleaning/deduper.py#L311">311</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/828da9083440ec5d5c154b6a7a6bafd0f025b84b/src/dfm/cleaning/deduper.py#L406">406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/828da9083440ec5d5c154b6a7a6bafd0f025b84b/src/dfm/cleaning/deduper.py#L421">421</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/828da9083440ec5d5c154b6a7a6bafd0f025b84b/src/dfm/cleaning/deduper.py#L444">444</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/828da9083440ec5d5c154b6a7a6bafd0f025b84b/src/dfm/cleaning/deduper.py#L549">549</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/828da9083440ec5d5c154b6a7a6bafd0f025b84b/src/dfm/cleaning/deduper.py#L576-L579">576&ndash;579</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/828da9083440ec5d5c154b6a7a6bafd0f025b84b/src/dfm/cleaning/deduper_utils.py">deduper_utils.py</a></td><td>26</td><td>3</td><td>88%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/828da9083440ec5d5c154b6a7a6bafd0f025b84b/src/dfm/cleaning/deduper_utils.py#L57-L60">57&ndash;60</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/828da9083440ec5d5c154b6a7a6bafd0f025b84b/src/dfm/cleaning/quality_filter.py">quality_filter.py</a></td><td>220</td><td>32</td><td>85%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/828da9083440ec5d5c154b6a7a6bafd0f025b84b/src/dfm/cleaning/quality_filter.py#L78-L83">78&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/828da9083440ec5d5c154b6a7a6bafd0f025b84b/src/dfm/cleaning/quality_filter.py#L264">264</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/828da9083440ec5d5c154b6a7a6bafd0f025b84b/src/dfm/cleaning/quality_filter.py#L269">269</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/828da9083440ec5d5c154b6a7a6bafd0f025b84b/src/dfm/cleaning/quality_filter.py#L343">343</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/828da9083440ec5d5c154b6a7a6bafd0f025b84b/src/dfm/cleaning/quality_filter.py#L352">352</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/828da9083440ec5d5c154b6a7a6bafd0f025b84b/src/dfm/cleaning/quality_filter.py#L391-L406">391&ndash;406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/828da9083440ec5d5c154b6a7a6bafd0f025b84b/src/dfm/cleaning/quality_filter.py#L539">539</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/828da9083440ec5d5c154b6a7a6bafd0f025b84b/src/dfm/cleaning/quality_filter.py#L572-L575">572&ndash;575</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/828da9083440ec5d5c154b6a7a6bafd0f025b84b/src/dfm/cleaning/quality_filter.py#L600">600</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/828da9083440ec5d5c154b6a7a6bafd0f025b84b/src/dfm/cleaning/quality_filter.py#L632">632</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/828da9083440ec5d5c154b6a7a6bafd0f025b84b/src/dfm/cleaning/quality_filter.py#L716">716</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/828da9083440ec5d5c154b6a7a6bafd0f025b84b/src/dfm/cleaning/quality_filter.py#L730">730</a></td></tr><tr><td colspan="5"><b>src/dfm/data</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/828da9083440ec5d5c154b6a7a6bafd0f025b84b/src/dfm/data/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/828da9083440ec5d5c154b6a7a6bafd0f025b84b/src/dfm/data/hate_speech.py">hate_speech.py</a></td><td>11</td><td>11</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/828da9083440ec5d5c154b6a7a6bafd0f025b84b/src/dfm/data/hate_speech.py#L1-L20">1&ndash;20</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/828da9083440ec5d5c154b6a7a6bafd0f025b84b/src/dfm/data/load.py">load.py</a></td><td>106</td><td>91</td><td>14%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/828da9083440ec5d5c154b6a7a6bafd0f025b84b/src/dfm/data/load.py#L35-L50">35&ndash;50</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/828da9083440ec5d5c154b6a7a6bafd0f025b84b/src/dfm/data/load.py#L59-L83">59&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/828da9083440ec5d5c154b6a7a6bafd0f025b84b/src/dfm/data/load.py#L98-L119">98&ndash;119</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/828da9083440ec5d5c154b6a7a6bafd0f025b84b/src/dfm [...]

2022-06-21 10:18 UTC, KennethEnevoldsen commented
<!-- Pytest Coverage Comment: pytest-coverage -->
<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/a0492a01c9fe0c4036515db42cd690aeaf4a2d95/README.md"><img alt="Coverage" src="https://img.shields.io/badge/Coverage-60%25-yellow.svg" /></a><br/><details><summary>Coverage Report</summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>src/dfm</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/a0492a01c9fe0c4036515db42cd690aeaf4a2d95/src/dfm/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/a0492a01c9fe0c4036515db42cd690aeaf4a2d95/src/dfm/train.py">train.py</a></td><td>68</td><td>68</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/a0492a01c9fe0c4036515db42cd690aeaf4a2d95/src/dfm/train.py#L14-L226">14&ndash;226</a></td></tr><tr><td colspan="5"><b>src/dfm/cleaning</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/a0492a01c9fe0c4036515db42cd690aeaf4a2d95/src/dfm/cleaning/__init__.py">__init__.py</a></td><td>2</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/a0492a01c9fe0c4036515db42cd690aeaf4a2d95/src/dfm/cleaning/deduper.py">deduper.py</a></td><td>156</td><td>16</td><td>90%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/a0492a01c9fe0c4036515db42cd690aeaf4a2d95/src/dfm/cleaning/deduper.py#L119-L124">119&ndash;124</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/a0492a01c9fe0c4036515db42cd690aeaf4a2d95/src/dfm/cleaning/deduper.py#L147">147</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/a0492a01c9fe0c4036515db42cd690aeaf4a2d95/src/dfm/cleaning/deduper.py#L275">275</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/a0492a01c9fe0c4036515db42cd690aeaf4a2d95/src/dfm/cleaning/deduper.py#L278">278</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/a0492a01c9fe0c4036515db42cd690aeaf4a2d95/src/dfm/cleaning/deduper.py#L311">311</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/a0492a01c9fe0c4036515db42cd690aeaf4a2d95/src/dfm/cleaning/deduper.py#L406">406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/a0492a01c9fe0c4036515db42cd690aeaf4a2d95/src/dfm/cleaning/deduper.py#L421">421</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/a0492a01c9fe0c4036515db42cd690aeaf4a2d95/src/dfm/cleaning/deduper.py#L444">444</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/a0492a01c9fe0c4036515db42cd690aeaf4a2d95/src/dfm/cleaning/deduper.py#L549">549</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/a0492a01c9fe0c4036515db42cd690aeaf4a2d95/src/dfm/cleaning/deduper.py#L576-L579">576&ndash;579</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/a0492a01c9fe0c4036515db42cd690aeaf4a2d95/src/dfm/cleaning/deduper_utils.py">deduper_utils.py</a></td><td>26</td><td>3</td><td>88%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/a0492a01c9fe0c4036515db42cd690aeaf4a2d95/src/dfm/cleaning/deduper_utils.py#L57-L60">57&ndash;60</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/a0492a01c9fe0c4036515db42cd690aeaf4a2d95/src/dfm/cleaning/quality_filter.py">quality_filter.py</a></td><td>220</td><td>32</td><td>85%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/a0492a01c9fe0c4036515db42cd690aeaf4a2d95/src/dfm/cleaning/quality_filter.py#L78-L83">78&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/a0492a01c9fe0c4036515db42cd690aeaf4a2d95/src/dfm/cleaning/quality_filter.py#L264">264</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/a0492a01c9fe0c4036515db42cd690aeaf4a2d95/src/dfm/cleaning/quality_filter.py#L269">269</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/a0492a01c9fe0c4036515db42cd690aeaf4a2d95/src/dfm/cleaning/quality_filter.py#L343">343</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/a0492a01c9fe0c4036515db42cd690aeaf4a2d95/src/dfm/cleaning/quality_filter.py#L352">352</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/a0492a01c9fe0c4036515db42cd690aeaf4a2d95/src/dfm/cleaning/quality_filter.py#L391-L406">391&ndash;406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/a0492a01c9fe0c4036515db42cd690aeaf4a2d95/src/dfm/cleaning/quality_filter.py#L539">539</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/a0492a01c9fe0c4036515db42cd690aeaf4a2d95/src/dfm/cleaning/quality_filter.py#L572-L575">572&ndash;575</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/a0492a01c9fe0c4036515db42cd690aeaf4a2d95/src/dfm/cleaning/quality_filter.py#L600">600</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/a0492a01c9fe0c4036515db42cd690aeaf4a2d95/src/dfm/cleaning/quality_filter.py#L632">632</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/a0492a01c9fe0c4036515db42cd690aeaf4a2d95/src/dfm/cleaning/quality_filter.py#L716">716</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/a0492a01c9fe0c4036515db42cd690aeaf4a2d95/src/dfm/cleaning/quality_filter.py#L730">730</a></td></tr><tr><td colspan="5"><b>src/dfm/data</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/a0492a01c9fe0c4036515db42cd690aeaf4a2d95/src/dfm/data/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/a0492a01c9fe0c4036515db42cd690aeaf4a2d95/src/dfm/data/hate_speech.py">hate_speech.py</a></td><td>11</td><td>11</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/a0492a01c9fe0c4036515db42cd690aeaf4a2d95/src/dfm/data/hate_speech.py#L1-L20">1&ndash;20</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/a0492a01c9fe0c4036515db42cd690aeaf4a2d95/src/dfm/data/load.py">load.py</a></td><td>106</td><td>91</td><td>14%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/a0492a01c9fe0c4036515db42cd690aeaf4a2d95/src/dfm/data/load.py#L35-L50">35&ndash;50</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/a0492a01c9fe0c4036515db42cd690aeaf4a2d95/src/dfm/data/load.py#L59-L83">59&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/a0492a01c9fe0c4036515db42cd690aeaf4a2d95/src/dfm/data/load.py#L98-L119">98&ndash;119</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/a0492a01c9fe0c4036515db42cd690aeaf4a2d95/src/dfm [...]

2022-06-21 10:22 UTC, KennethEnevoldsen commented
<!-- Pytest Coverage Comment: pytest-coverage -->
<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e16efdb258ea123b45963732dafaa4d390bc59f/README.md"><img alt="Coverage" src="https://img.shields.io/badge/Coverage-60%25-yellow.svg" /></a><br/><details><summary>Coverage Report</summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>src/dfm</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e16efdb258ea123b45963732dafaa4d390bc59f/src/dfm/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e16efdb258ea123b45963732dafaa4d390bc59f/src/dfm/train.py">train.py</a></td><td>68</td><td>68</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e16efdb258ea123b45963732dafaa4d390bc59f/src/dfm/train.py#L14-L226">14&ndash;226</a></td></tr><tr><td colspan="5"><b>src/dfm/cleaning</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e16efdb258ea123b45963732dafaa4d390bc59f/src/dfm/cleaning/__init__.py">__init__.py</a></td><td>2</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e16efdb258ea123b45963732dafaa4d390bc59f/src/dfm/cleaning/deduper.py">deduper.py</a></td><td>156</td><td>16</td><td>90%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e16efdb258ea123b45963732dafaa4d390bc59f/src/dfm/cleaning/deduper.py#L119-L124">119&ndash;124</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e16efdb258ea123b45963732dafaa4d390bc59f/src/dfm/cleaning/deduper.py#L147">147</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e16efdb258ea123b45963732dafaa4d390bc59f/src/dfm/cleaning/deduper.py#L275">275</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e16efdb258ea123b45963732dafaa4d390bc59f/src/dfm/cleaning/deduper.py#L278">278</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e16efdb258ea123b45963732dafaa4d390bc59f/src/dfm/cleaning/deduper.py#L311">311</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e16efdb258ea123b45963732dafaa4d390bc59f/src/dfm/cleaning/deduper.py#L406">406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e16efdb258ea123b45963732dafaa4d390bc59f/src/dfm/cleaning/deduper.py#L421">421</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e16efdb258ea123b45963732dafaa4d390bc59f/src/dfm/cleaning/deduper.py#L444">444</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e16efdb258ea123b45963732dafaa4d390bc59f/src/dfm/cleaning/deduper.py#L549">549</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e16efdb258ea123b45963732dafaa4d390bc59f/src/dfm/cleaning/deduper.py#L576-L579">576&ndash;579</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e16efdb258ea123b45963732dafaa4d390bc59f/src/dfm/cleaning/deduper_utils.py">deduper_utils.py</a></td><td>26</td><td>3</td><td>88%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e16efdb258ea123b45963732dafaa4d390bc59f/src/dfm/cleaning/deduper_utils.py#L57-L60">57&ndash;60</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e16efdb258ea123b45963732dafaa4d390bc59f/src/dfm/cleaning/quality_filter.py">quality_filter.py</a></td><td>220</td><td>32</td><td>85%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e16efdb258ea123b45963732dafaa4d390bc59f/src/dfm/cleaning/quality_filter.py#L78-L83">78&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e16efdb258ea123b45963732dafaa4d390bc59f/src/dfm/cleaning/quality_filter.py#L264">264</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e16efdb258ea123b45963732dafaa4d390bc59f/src/dfm/cleaning/quality_filter.py#L269">269</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e16efdb258ea123b45963732dafaa4d390bc59f/src/dfm/cleaning/quality_filter.py#L343">343</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e16efdb258ea123b45963732dafaa4d390bc59f/src/dfm/cleaning/quality_filter.py#L352">352</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e16efdb258ea123b45963732dafaa4d390bc59f/src/dfm/cleaning/quality_filter.py#L391-L406">391&ndash;406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e16efdb258ea123b45963732dafaa4d390bc59f/src/dfm/cleaning/quality_filter.py#L539">539</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e16efdb258ea123b45963732dafaa4d390bc59f/src/dfm/cleaning/quality_filter.py#L572-L575">572&ndash;575</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e16efdb258ea123b45963732dafaa4d390bc59f/src/dfm/cleaning/quality_filter.py#L600">600</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e16efdb258ea123b45963732dafaa4d390bc59f/src/dfm/cleaning/quality_filter.py#L632">632</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e16efdb258ea123b45963732dafaa4d390bc59f/src/dfm/cleaning/quality_filter.py#L716">716</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e16efdb258ea123b45963732dafaa4d390bc59f/src/dfm/cleaning/quality_filter.py#L730">730</a></td></tr><tr><td colspan="5"><b>src/dfm/data</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e16efdb258ea123b45963732dafaa4d390bc59f/src/dfm/data/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e16efdb258ea123b45963732dafaa4d390bc59f/src/dfm/data/hate_speech.py">hate_speech.py</a></td><td>11</td><td>11</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e16efdb258ea123b45963732dafaa4d390bc59f/src/dfm/data/hate_speech.py#L1-L20">1&ndash;20</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e16efdb258ea123b45963732dafaa4d390bc59f/src/dfm/data/load.py">load.py</a></td><td>106</td><td>91</td><td>14%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e16efdb258ea123b45963732dafaa4d390bc59f/src/dfm/data/load.py#L35-L50">35&ndash;50</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e16efdb258ea123b45963732dafaa4d390bc59f/src/dfm/data/load.py#L59-L83">59&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e16efdb258ea123b45963732dafaa4d390bc59f/src/dfm/data/load.py#L98-L119">98&ndash;119</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/0e16efdb258ea123b45963732dafaa4d390bc59f/src/dfm [...]

2022-06-21 10:57 UTC, KennethEnevoldsen commented
fixed typos and formatted to black

2022-06-21 10:59 UTC, KennethEnevoldsen commented
<!-- Pytest Coverage Comment: pytest-coverage -->
<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/181744d6562a18b7f8fb21266d820ec3c3507c21/README.md"><img alt="Coverage" src="https://img.shields.io/badge/Coverage-60%25-yellow.svg" /></a><br/><details><summary>Coverage Report</summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>src/dfm</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/181744d6562a18b7f8fb21266d820ec3c3507c21/src/dfm/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/181744d6562a18b7f8fb21266d820ec3c3507c21/src/dfm/train.py">train.py</a></td><td>68</td><td>68</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/181744d6562a18b7f8fb21266d820ec3c3507c21/src/dfm/train.py#L14-L226">14&ndash;226</a></td></tr><tr><td colspan="5"><b>src/dfm/cleaning</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/181744d6562a18b7f8fb21266d820ec3c3507c21/src/dfm/cleaning/__init__.py">__init__.py</a></td><td>2</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/181744d6562a18b7f8fb21266d820ec3c3507c21/src/dfm/cleaning/deduper.py">deduper.py</a></td><td>156</td><td>16</td><td>90%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/181744d6562a18b7f8fb21266d820ec3c3507c21/src/dfm/cleaning/deduper.py#L119-L124">119&ndash;124</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/181744d6562a18b7f8fb21266d820ec3c3507c21/src/dfm/cleaning/deduper.py#L147">147</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/181744d6562a18b7f8fb21266d820ec3c3507c21/src/dfm/cleaning/deduper.py#L275">275</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/181744d6562a18b7f8fb21266d820ec3c3507c21/src/dfm/cleaning/deduper.py#L278">278</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/181744d6562a18b7f8fb21266d820ec3c3507c21/src/dfm/cleaning/deduper.py#L311">311</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/181744d6562a18b7f8fb21266d820ec3c3507c21/src/dfm/cleaning/deduper.py#L406">406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/181744d6562a18b7f8fb21266d820ec3c3507c21/src/dfm/cleaning/deduper.py#L421">421</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/181744d6562a18b7f8fb21266d820ec3c3507c21/src/dfm/cleaning/deduper.py#L444">444</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/181744d6562a18b7f8fb21266d820ec3c3507c21/src/dfm/cleaning/deduper.py#L549">549</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/181744d6562a18b7f8fb21266d820ec3c3507c21/src/dfm/cleaning/deduper.py#L576-L579">576&ndash;579</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/181744d6562a18b7f8fb21266d820ec3c3507c21/src/dfm/cleaning/deduper_utils.py">deduper_utils.py</a></td><td>26</td><td>3</td><td>88%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/181744d6562a18b7f8fb21266d820ec3c3507c21/src/dfm/cleaning/deduper_utils.py#L57-L60">57&ndash;60</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/181744d6562a18b7f8fb21266d820ec3c3507c21/src/dfm/cleaning/quality_filter.py">quality_filter.py</a></td><td>220</td><td>32</td><td>85%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/181744d6562a18b7f8fb21266d820ec3c3507c21/src/dfm/cleaning/quality_filter.py#L78-L83">78&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/181744d6562a18b7f8fb21266d820ec3c3507c21/src/dfm/cleaning/quality_filter.py#L264">264</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/181744d6562a18b7f8fb21266d820ec3c3507c21/src/dfm/cleaning/quality_filter.py#L269">269</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/181744d6562a18b7f8fb21266d820ec3c3507c21/src/dfm/cleaning/quality_filter.py#L343">343</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/181744d6562a18b7f8fb21266d820ec3c3507c21/src/dfm/cleaning/quality_filter.py#L352">352</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/181744d6562a18b7f8fb21266d820ec3c3507c21/src/dfm/cleaning/quality_filter.py#L391-L406">391&ndash;406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/181744d6562a18b7f8fb21266d820ec3c3507c21/src/dfm/cleaning/quality_filter.py#L539">539</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/181744d6562a18b7f8fb21266d820ec3c3507c21/src/dfm/cleaning/quality_filter.py#L572-L575">572&ndash;575</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/181744d6562a18b7f8fb21266d820ec3c3507c21/src/dfm/cleaning/quality_filter.py#L600">600</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/181744d6562a18b7f8fb21266d820ec3c3507c21/src/dfm/cleaning/quality_filter.py#L632">632</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/181744d6562a18b7f8fb21266d820ec3c3507c21/src/dfm/cleaning/quality_filter.py#L716">716</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/181744d6562a18b7f8fb21266d820ec3c3507c21/src/dfm/cleaning/quality_filter.py#L730">730</a></td></tr><tr><td colspan="5"><b>src/dfm/data</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/181744d6562a18b7f8fb21266d820ec3c3507c21/src/dfm/data/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/181744d6562a18b7f8fb21266d820ec3c3507c21/src/dfm/data/hate_speech.py">hate_speech.py</a></td><td>11</td><td>11</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/181744d6562a18b7f8fb21266d820ec3c3507c21/src/dfm/data/hate_speech.py#L1-L20">1&ndash;20</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/181744d6562a18b7f8fb21266d820ec3c3507c21/src/dfm/data/load.py">load.py</a></td><td>106</td><td>91</td><td>14%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/181744d6562a18b7f8fb21266d820ec3c3507c21/src/dfm/data/load.py#L35-L50">35&ndash;50</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/181744d6562a18b7f8fb21266d820ec3c3507c21/src/dfm/data/load.py#L59-L83">59&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/181744d6562a18b7f8fb21266d820ec3c3507c21/src/dfm/data/load.py#L98-L119">98&ndash;119</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/181744d6562a18b7f8fb21266d820ec3c3507c21/src/dfm [...]

2022-06-21 15:43 UTC, saattrupdan requested changes
Still a couple of smaller points, and a few of my previous comments have not been resolved yet.

2022-06-21 15:43 UTC, saattrupdan commented on docs/datasheets/Netarkivet_text.md
> +The sites which passed the quality filter were deduplicated pr. year. NAT consist of 865 billion tokens of which 134 (0.16%) billion were left after filtering and deduplication.
```suggestion
The sites which passed the quality filter were deduplicated per year. NAT consist of 865 billion tokens of which 134 (15%) billion were left after filtering and deduplication.
```

2022-06-21 15:43 UTC, saattrupdan commented on docs/datasheets/Netarkivet_text.md
> +**If the dataset is a sample from a larger set, what was the sampling strategy?**
```suggestion

**If the dataset is a sample from a larger set, what was the sampling strategy?**
```

2022-06-21 15:43 UTC, saattrupdan commented on docs/datasheets/Netarkivet_text.md
> +
```suggestion

```

2022-06-21 15:43 UTC, saattrupdan commented on docs/datasheets/Netarkivet_text.md
> +
```suggestion
```

2022-06-23 06:54 UTC, KennethEnevoldsen commented
<!-- Pytest Coverage Comment: pytest-coverage -->
<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/fdad33891d043b0ab868bdce658dc52c93e10d92/README.md"><img alt="Coverage" src="https://img.shields.io/badge/Coverage-60%25-yellow.svg" /></a><br/><details><summary>Coverage Report</summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>src/dfm</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/fdad33891d043b0ab868bdce658dc52c93e10d92/src/dfm/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/fdad33891d043b0ab868bdce658dc52c93e10d92/src/dfm/train.py">train.py</a></td><td>68</td><td>68</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/fdad33891d043b0ab868bdce658dc52c93e10d92/src/dfm/train.py#L14-L226">14&ndash;226</a></td></tr><tr><td colspan="5"><b>src/dfm/cleaning</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/fdad33891d043b0ab868bdce658dc52c93e10d92/src/dfm/cleaning/__init__.py">__init__.py</a></td><td>2</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/fdad33891d043b0ab868bdce658dc52c93e10d92/src/dfm/cleaning/deduper.py">deduper.py</a></td><td>156</td><td>16</td><td>90%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/fdad33891d043b0ab868bdce658dc52c93e10d92/src/dfm/cleaning/deduper.py#L119-L124">119&ndash;124</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/fdad33891d043b0ab868bdce658dc52c93e10d92/src/dfm/cleaning/deduper.py#L147">147</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/fdad33891d043b0ab868bdce658dc52c93e10d92/src/dfm/cleaning/deduper.py#L275">275</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/fdad33891d043b0ab868bdce658dc52c93e10d92/src/dfm/cleaning/deduper.py#L278">278</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/fdad33891d043b0ab868bdce658dc52c93e10d92/src/dfm/cleaning/deduper.py#L311">311</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/fdad33891d043b0ab868bdce658dc52c93e10d92/src/dfm/cleaning/deduper.py#L406">406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/fdad33891d043b0ab868bdce658dc52c93e10d92/src/dfm/cleaning/deduper.py#L421">421</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/fdad33891d043b0ab868bdce658dc52c93e10d92/src/dfm/cleaning/deduper.py#L444">444</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/fdad33891d043b0ab868bdce658dc52c93e10d92/src/dfm/cleaning/deduper.py#L549">549</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/fdad33891d043b0ab868bdce658dc52c93e10d92/src/dfm/cleaning/deduper.py#L576-L579">576&ndash;579</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/fdad33891d043b0ab868bdce658dc52c93e10d92/src/dfm/cleaning/deduper_utils.py">deduper_utils.py</a></td><td>26</td><td>3</td><td>88%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/fdad33891d043b0ab868bdce658dc52c93e10d92/src/dfm/cleaning/deduper_utils.py#L57-L60">57&ndash;60</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/fdad33891d043b0ab868bdce658dc52c93e10d92/src/dfm/cleaning/quality_filter.py">quality_filter.py</a></td><td>220</td><td>32</td><td>85%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/fdad33891d043b0ab868bdce658dc52c93e10d92/src/dfm/cleaning/quality_filter.py#L78-L83">78&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/fdad33891d043b0ab868bdce658dc52c93e10d92/src/dfm/cleaning/quality_filter.py#L264">264</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/fdad33891d043b0ab868bdce658dc52c93e10d92/src/dfm/cleaning/quality_filter.py#L269">269</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/fdad33891d043b0ab868bdce658dc52c93e10d92/src/dfm/cleaning/quality_filter.py#L343">343</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/fdad33891d043b0ab868bdce658dc52c93e10d92/src/dfm/cleaning/quality_filter.py#L352">352</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/fdad33891d043b0ab868bdce658dc52c93e10d92/src/dfm/cleaning/quality_filter.py#L391-L406">391&ndash;406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/fdad33891d043b0ab868bdce658dc52c93e10d92/src/dfm/cleaning/quality_filter.py#L539">539</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/fdad33891d043b0ab868bdce658dc52c93e10d92/src/dfm/cleaning/quality_filter.py#L572-L575">572&ndash;575</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/fdad33891d043b0ab868bdce658dc52c93e10d92/src/dfm/cleaning/quality_filter.py#L600">600</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/fdad33891d043b0ab868bdce658dc52c93e10d92/src/dfm/cleaning/quality_filter.py#L632">632</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/fdad33891d043b0ab868bdce658dc52c93e10d92/src/dfm/cleaning/quality_filter.py#L716">716</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/fdad33891d043b0ab868bdce658dc52c93e10d92/src/dfm/cleaning/quality_filter.py#L730">730</a></td></tr><tr><td colspan="5"><b>src/dfm/data</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/fdad33891d043b0ab868bdce658dc52c93e10d92/src/dfm/data/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/fdad33891d043b0ab868bdce658dc52c93e10d92/src/dfm/data/hate_speech.py">hate_speech.py</a></td><td>11</td><td>11</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/fdad33891d043b0ab868bdce658dc52c93e10d92/src/dfm/data/hate_speech.py#L1-L20">1&ndash;20</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/fdad33891d043b0ab868bdce658dc52c93e10d92/src/dfm/data/load.py">load.py</a></td><td>106</td><td>91</td><td>14%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/fdad33891d043b0ab868bdce658dc52c93e10d92/src/dfm/data/load.py#L35-L50">35&ndash;50</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/fdad33891d043b0ab868bdce658dc52c93e10d92/src/dfm/data/load.py#L59-L83">59&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/fdad33891d043b0ab868bdce658dc52c93e10d92/src/dfm/data/load.py#L98-L119">98&ndash;119</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/fdad33891d043b0ab868bdce658dc52c93e10d92/src/dfm [...]

2022-06-23 06:54 UTC, KennethEnevoldsen commented
<!-- Pytest Coverage Comment: pytest-coverage -->
<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/9518eacc2b388b53f183b57c3c5754dca28e56ca/README.md"><img alt="Coverage" src="https://img.shields.io/badge/Coverage-60%25-yellow.svg" /></a><br/><details><summary>Coverage Report</summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>src/dfm</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/9518eacc2b388b53f183b57c3c5754dca28e56ca/src/dfm/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/9518eacc2b388b53f183b57c3c5754dca28e56ca/src/dfm/train.py">train.py</a></td><td>68</td><td>68</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/9518eacc2b388b53f183b57c3c5754dca28e56ca/src/dfm/train.py#L14-L226">14&ndash;226</a></td></tr><tr><td colspan="5"><b>src/dfm/cleaning</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/9518eacc2b388b53f183b57c3c5754dca28e56ca/src/dfm/cleaning/__init__.py">__init__.py</a></td><td>2</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/9518eacc2b388b53f183b57c3c5754dca28e56ca/src/dfm/cleaning/deduper.py">deduper.py</a></td><td>156</td><td>16</td><td>90%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/9518eacc2b388b53f183b57c3c5754dca28e56ca/src/dfm/cleaning/deduper.py#L119-L124">119&ndash;124</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/9518eacc2b388b53f183b57c3c5754dca28e56ca/src/dfm/cleaning/deduper.py#L147">147</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/9518eacc2b388b53f183b57c3c5754dca28e56ca/src/dfm/cleaning/deduper.py#L275">275</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/9518eacc2b388b53f183b57c3c5754dca28e56ca/src/dfm/cleaning/deduper.py#L278">278</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/9518eacc2b388b53f183b57c3c5754dca28e56ca/src/dfm/cleaning/deduper.py#L311">311</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/9518eacc2b388b53f183b57c3c5754dca28e56ca/src/dfm/cleaning/deduper.py#L406">406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/9518eacc2b388b53f183b57c3c5754dca28e56ca/src/dfm/cleaning/deduper.py#L421">421</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/9518eacc2b388b53f183b57c3c5754dca28e56ca/src/dfm/cleaning/deduper.py#L444">444</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/9518eacc2b388b53f183b57c3c5754dca28e56ca/src/dfm/cleaning/deduper.py#L549">549</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/9518eacc2b388b53f183b57c3c5754dca28e56ca/src/dfm/cleaning/deduper.py#L576-L579">576&ndash;579</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/9518eacc2b388b53f183b57c3c5754dca28e56ca/src/dfm/cleaning/deduper_utils.py">deduper_utils.py</a></td><td>26</td><td>3</td><td>88%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/9518eacc2b388b53f183b57c3c5754dca28e56ca/src/dfm/cleaning/deduper_utils.py#L57-L60">57&ndash;60</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/9518eacc2b388b53f183b57c3c5754dca28e56ca/src/dfm/cleaning/quality_filter.py">quality_filter.py</a></td><td>220</td><td>32</td><td>85%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/9518eacc2b388b53f183b57c3c5754dca28e56ca/src/dfm/cleaning/quality_filter.py#L78-L83">78&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/9518eacc2b388b53f183b57c3c5754dca28e56ca/src/dfm/cleaning/quality_filter.py#L264">264</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/9518eacc2b388b53f183b57c3c5754dca28e56ca/src/dfm/cleaning/quality_filter.py#L269">269</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/9518eacc2b388b53f183b57c3c5754dca28e56ca/src/dfm/cleaning/quality_filter.py#L343">343</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/9518eacc2b388b53f183b57c3c5754dca28e56ca/src/dfm/cleaning/quality_filter.py#L352">352</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/9518eacc2b388b53f183b57c3c5754dca28e56ca/src/dfm/cleaning/quality_filter.py#L391-L406">391&ndash;406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/9518eacc2b388b53f183b57c3c5754dca28e56ca/src/dfm/cleaning/quality_filter.py#L539">539</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/9518eacc2b388b53f183b57c3c5754dca28e56ca/src/dfm/cleaning/quality_filter.py#L572-L575">572&ndash;575</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/9518eacc2b388b53f183b57c3c5754dca28e56ca/src/dfm/cleaning/quality_filter.py#L600">600</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/9518eacc2b388b53f183b57c3c5754dca28e56ca/src/dfm/cleaning/quality_filter.py#L632">632</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/9518eacc2b388b53f183b57c3c5754dca28e56ca/src/dfm/cleaning/quality_filter.py#L716">716</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/9518eacc2b388b53f183b57c3c5754dca28e56ca/src/dfm/cleaning/quality_filter.py#L730">730</a></td></tr><tr><td colspan="5"><b>src/dfm/data</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/9518eacc2b388b53f183b57c3c5754dca28e56ca/src/dfm/data/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/9518eacc2b388b53f183b57c3c5754dca28e56ca/src/dfm/data/hate_speech.py">hate_speech.py</a></td><td>11</td><td>11</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/9518eacc2b388b53f183b57c3c5754dca28e56ca/src/dfm/data/hate_speech.py#L1-L20">1&ndash;20</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/9518eacc2b388b53f183b57c3c5754dca28e56ca/src/dfm/data/load.py">load.py</a></td><td>106</td><td>91</td><td>14%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/9518eacc2b388b53f183b57c3c5754dca28e56ca/src/dfm/data/load.py#L35-L50">35&ndash;50</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/9518eacc2b388b53f183b57c3c5754dca28e56ca/src/dfm/data/load.py#L59-L83">59&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/9518eacc2b388b53f183b57c3c5754dca28e56ca/src/dfm/data/load.py#L98-L119">98&ndash;119</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/9518eacc2b388b53f183b57c3c5754dca28e56ca/src/dfm [...]

2022-06-23 06:54 UTC, KennethEnevoldsen commented
<!-- Pytest Coverage Comment: pytest-coverage -->
<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/51af51b422844049512b3c7d722f95c71c82ed74/README.md"><img alt="Coverage" src="https://img.shields.io/badge/Coverage-60%25-yellow.svg" /></a><br/><details><summary>Coverage Report</summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>src/dfm</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/51af51b422844049512b3c7d722f95c71c82ed74/src/dfm/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/51af51b422844049512b3c7d722f95c71c82ed74/src/dfm/train.py">train.py</a></td><td>68</td><td>68</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/51af51b422844049512b3c7d722f95c71c82ed74/src/dfm/train.py#L14-L226">14&ndash;226</a></td></tr><tr><td colspan="5"><b>src/dfm/cleaning</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/51af51b422844049512b3c7d722f95c71c82ed74/src/dfm/cleaning/__init__.py">__init__.py</a></td><td>2</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/51af51b422844049512b3c7d722f95c71c82ed74/src/dfm/cleaning/deduper.py">deduper.py</a></td><td>156</td><td>16</td><td>90%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/51af51b422844049512b3c7d722f95c71c82ed74/src/dfm/cleaning/deduper.py#L119-L124">119&ndash;124</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/51af51b422844049512b3c7d722f95c71c82ed74/src/dfm/cleaning/deduper.py#L147">147</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/51af51b422844049512b3c7d722f95c71c82ed74/src/dfm/cleaning/deduper.py#L275">275</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/51af51b422844049512b3c7d722f95c71c82ed74/src/dfm/cleaning/deduper.py#L278">278</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/51af51b422844049512b3c7d722f95c71c82ed74/src/dfm/cleaning/deduper.py#L311">311</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/51af51b422844049512b3c7d722f95c71c82ed74/src/dfm/cleaning/deduper.py#L406">406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/51af51b422844049512b3c7d722f95c71c82ed74/src/dfm/cleaning/deduper.py#L421">421</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/51af51b422844049512b3c7d722f95c71c82ed74/src/dfm/cleaning/deduper.py#L444">444</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/51af51b422844049512b3c7d722f95c71c82ed74/src/dfm/cleaning/deduper.py#L549">549</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/51af51b422844049512b3c7d722f95c71c82ed74/src/dfm/cleaning/deduper.py#L576-L579">576&ndash;579</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/51af51b422844049512b3c7d722f95c71c82ed74/src/dfm/cleaning/deduper_utils.py">deduper_utils.py</a></td><td>26</td><td>3</td><td>88%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/51af51b422844049512b3c7d722f95c71c82ed74/src/dfm/cleaning/deduper_utils.py#L57-L60">57&ndash;60</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/51af51b422844049512b3c7d722f95c71c82ed74/src/dfm/cleaning/quality_filter.py">quality_filter.py</a></td><td>220</td><td>32</td><td>85%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/51af51b422844049512b3c7d722f95c71c82ed74/src/dfm/cleaning/quality_filter.py#L78-L83">78&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/51af51b422844049512b3c7d722f95c71c82ed74/src/dfm/cleaning/quality_filter.py#L264">264</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/51af51b422844049512b3c7d722f95c71c82ed74/src/dfm/cleaning/quality_filter.py#L269">269</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/51af51b422844049512b3c7d722f95c71c82ed74/src/dfm/cleaning/quality_filter.py#L343">343</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/51af51b422844049512b3c7d722f95c71c82ed74/src/dfm/cleaning/quality_filter.py#L352">352</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/51af51b422844049512b3c7d722f95c71c82ed74/src/dfm/cleaning/quality_filter.py#L391-L406">391&ndash;406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/51af51b422844049512b3c7d722f95c71c82ed74/src/dfm/cleaning/quality_filter.py#L539">539</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/51af51b422844049512b3c7d722f95c71c82ed74/src/dfm/cleaning/quality_filter.py#L572-L575">572&ndash;575</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/51af51b422844049512b3c7d722f95c71c82ed74/src/dfm/cleaning/quality_filter.py#L600">600</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/51af51b422844049512b3c7d722f95c71c82ed74/src/dfm/cleaning/quality_filter.py#L632">632</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/51af51b422844049512b3c7d722f95c71c82ed74/src/dfm/cleaning/quality_filter.py#L716">716</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/51af51b422844049512b3c7d722f95c71c82ed74/src/dfm/cleaning/quality_filter.py#L730">730</a></td></tr><tr><td colspan="5"><b>src/dfm/data</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/51af51b422844049512b3c7d722f95c71c82ed74/src/dfm/data/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/51af51b422844049512b3c7d722f95c71c82ed74/src/dfm/data/hate_speech.py">hate_speech.py</a></td><td>11</td><td>11</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/51af51b422844049512b3c7d722f95c71c82ed74/src/dfm/data/hate_speech.py#L1-L20">1&ndash;20</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/51af51b422844049512b3c7d722f95c71c82ed74/src/dfm/data/load.py">load.py</a></td><td>106</td><td>91</td><td>14%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/51af51b422844049512b3c7d722f95c71c82ed74/src/dfm/data/load.py#L35-L50">35&ndash;50</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/51af51b422844049512b3c7d722f95c71c82ed74/src/dfm/data/load.py#L59-L83">59&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/51af51b422844049512b3c7d722f95c71c82ed74/src/dfm/data/load.py#L98-L119">98&ndash;119</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/51af51b422844049512b3c7d722f95c71c82ed74/src/dfm [...]

2022-06-23 06:55 UTC, KennethEnevoldsen commented
<!-- Pytest Coverage Comment: pytest-coverage -->
<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8c58e592d7ebe2529b682a86641ab422e1e053f2/README.md"><img alt="Coverage" src="https://img.shields.io/badge/Coverage-60%25-yellow.svg" /></a><br/><details><summary>Coverage Report</summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>src/dfm</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8c58e592d7ebe2529b682a86641ab422e1e053f2/src/dfm/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8c58e592d7ebe2529b682a86641ab422e1e053f2/src/dfm/train.py">train.py</a></td><td>68</td><td>68</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8c58e592d7ebe2529b682a86641ab422e1e053f2/src/dfm/train.py#L14-L226">14&ndash;226</a></td></tr><tr><td colspan="5"><b>src/dfm/cleaning</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8c58e592d7ebe2529b682a86641ab422e1e053f2/src/dfm/cleaning/__init__.py">__init__.py</a></td><td>2</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8c58e592d7ebe2529b682a86641ab422e1e053f2/src/dfm/cleaning/deduper.py">deduper.py</a></td><td>156</td><td>16</td><td>90%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8c58e592d7ebe2529b682a86641ab422e1e053f2/src/dfm/cleaning/deduper.py#L119-L124">119&ndash;124</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8c58e592d7ebe2529b682a86641ab422e1e053f2/src/dfm/cleaning/deduper.py#L147">147</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8c58e592d7ebe2529b682a86641ab422e1e053f2/src/dfm/cleaning/deduper.py#L275">275</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8c58e592d7ebe2529b682a86641ab422e1e053f2/src/dfm/cleaning/deduper.py#L278">278</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8c58e592d7ebe2529b682a86641ab422e1e053f2/src/dfm/cleaning/deduper.py#L311">311</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8c58e592d7ebe2529b682a86641ab422e1e053f2/src/dfm/cleaning/deduper.py#L406">406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8c58e592d7ebe2529b682a86641ab422e1e053f2/src/dfm/cleaning/deduper.py#L421">421</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8c58e592d7ebe2529b682a86641ab422e1e053f2/src/dfm/cleaning/deduper.py#L444">444</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8c58e592d7ebe2529b682a86641ab422e1e053f2/src/dfm/cleaning/deduper.py#L549">549</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8c58e592d7ebe2529b682a86641ab422e1e053f2/src/dfm/cleaning/deduper.py#L576-L579">576&ndash;579</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8c58e592d7ebe2529b682a86641ab422e1e053f2/src/dfm/cleaning/deduper_utils.py">deduper_utils.py</a></td><td>26</td><td>3</td><td>88%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8c58e592d7ebe2529b682a86641ab422e1e053f2/src/dfm/cleaning/deduper_utils.py#L57-L60">57&ndash;60</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8c58e592d7ebe2529b682a86641ab422e1e053f2/src/dfm/cleaning/quality_filter.py">quality_filter.py</a></td><td>220</td><td>32</td><td>85%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8c58e592d7ebe2529b682a86641ab422e1e053f2/src/dfm/cleaning/quality_filter.py#L78-L83">78&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8c58e592d7ebe2529b682a86641ab422e1e053f2/src/dfm/cleaning/quality_filter.py#L264">264</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8c58e592d7ebe2529b682a86641ab422e1e053f2/src/dfm/cleaning/quality_filter.py#L269">269</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8c58e592d7ebe2529b682a86641ab422e1e053f2/src/dfm/cleaning/quality_filter.py#L343">343</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8c58e592d7ebe2529b682a86641ab422e1e053f2/src/dfm/cleaning/quality_filter.py#L352">352</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8c58e592d7ebe2529b682a86641ab422e1e053f2/src/dfm/cleaning/quality_filter.py#L391-L406">391&ndash;406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8c58e592d7ebe2529b682a86641ab422e1e053f2/src/dfm/cleaning/quality_filter.py#L539">539</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8c58e592d7ebe2529b682a86641ab422e1e053f2/src/dfm/cleaning/quality_filter.py#L572-L575">572&ndash;575</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8c58e592d7ebe2529b682a86641ab422e1e053f2/src/dfm/cleaning/quality_filter.py#L600">600</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8c58e592d7ebe2529b682a86641ab422e1e053f2/src/dfm/cleaning/quality_filter.py#L632">632</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8c58e592d7ebe2529b682a86641ab422e1e053f2/src/dfm/cleaning/quality_filter.py#L716">716</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8c58e592d7ebe2529b682a86641ab422e1e053f2/src/dfm/cleaning/quality_filter.py#L730">730</a></td></tr><tr><td colspan="5"><b>src/dfm/data</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8c58e592d7ebe2529b682a86641ab422e1e053f2/src/dfm/data/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8c58e592d7ebe2529b682a86641ab422e1e053f2/src/dfm/data/hate_speech.py">hate_speech.py</a></td><td>11</td><td>11</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8c58e592d7ebe2529b682a86641ab422e1e053f2/src/dfm/data/hate_speech.py#L1-L20">1&ndash;20</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8c58e592d7ebe2529b682a86641ab422e1e053f2/src/dfm/data/load.py">load.py</a></td><td>106</td><td>91</td><td>14%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8c58e592d7ebe2529b682a86641ab422e1e053f2/src/dfm/data/load.py#L35-L50">35&ndash;50</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8c58e592d7ebe2529b682a86641ab422e1e053f2/src/dfm/data/load.py#L59-L83">59&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8c58e592d7ebe2529b682a86641ab422e1e053f2/src/dfm/data/load.py#L98-L119">98&ndash;119</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/8c58e592d7ebe2529b682a86641ab422e1e053f2/src/dfm [...]

2022-06-23 06:57 UTC, KennethEnevoldsen commented
<!-- Pytest Coverage Comment: pytest-coverage -->
<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/52d6d0d81c44693dd90641111493886fb22f6f11/README.md"><img alt="Coverage" src="https://img.shields.io/badge/Coverage-60%25-yellow.svg" /></a><br/><details><summary>Coverage Report</summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>src/dfm</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/52d6d0d81c44693dd90641111493886fb22f6f11/src/dfm/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/52d6d0d81c44693dd90641111493886fb22f6f11/src/dfm/train.py">train.py</a></td><td>68</td><td>68</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/52d6d0d81c44693dd90641111493886fb22f6f11/src/dfm/train.py#L14-L226">14&ndash;226</a></td></tr><tr><td colspan="5"><b>src/dfm/cleaning</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/52d6d0d81c44693dd90641111493886fb22f6f11/src/dfm/cleaning/__init__.py">__init__.py</a></td><td>2</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/52d6d0d81c44693dd90641111493886fb22f6f11/src/dfm/cleaning/deduper.py">deduper.py</a></td><td>156</td><td>16</td><td>90%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/52d6d0d81c44693dd90641111493886fb22f6f11/src/dfm/cleaning/deduper.py#L119-L124">119&ndash;124</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/52d6d0d81c44693dd90641111493886fb22f6f11/src/dfm/cleaning/deduper.py#L147">147</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/52d6d0d81c44693dd90641111493886fb22f6f11/src/dfm/cleaning/deduper.py#L275">275</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/52d6d0d81c44693dd90641111493886fb22f6f11/src/dfm/cleaning/deduper.py#L278">278</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/52d6d0d81c44693dd90641111493886fb22f6f11/src/dfm/cleaning/deduper.py#L311">311</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/52d6d0d81c44693dd90641111493886fb22f6f11/src/dfm/cleaning/deduper.py#L406">406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/52d6d0d81c44693dd90641111493886fb22f6f11/src/dfm/cleaning/deduper.py#L421">421</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/52d6d0d81c44693dd90641111493886fb22f6f11/src/dfm/cleaning/deduper.py#L444">444</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/52d6d0d81c44693dd90641111493886fb22f6f11/src/dfm/cleaning/deduper.py#L549">549</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/52d6d0d81c44693dd90641111493886fb22f6f11/src/dfm/cleaning/deduper.py#L576-L579">576&ndash;579</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/52d6d0d81c44693dd90641111493886fb22f6f11/src/dfm/cleaning/deduper_utils.py">deduper_utils.py</a></td><td>26</td><td>3</td><td>88%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/52d6d0d81c44693dd90641111493886fb22f6f11/src/dfm/cleaning/deduper_utils.py#L57-L60">57&ndash;60</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/52d6d0d81c44693dd90641111493886fb22f6f11/src/dfm/cleaning/quality_filter.py">quality_filter.py</a></td><td>220</td><td>32</td><td>85%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/52d6d0d81c44693dd90641111493886fb22f6f11/src/dfm/cleaning/quality_filter.py#L78-L83">78&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/52d6d0d81c44693dd90641111493886fb22f6f11/src/dfm/cleaning/quality_filter.py#L264">264</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/52d6d0d81c44693dd90641111493886fb22f6f11/src/dfm/cleaning/quality_filter.py#L269">269</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/52d6d0d81c44693dd90641111493886fb22f6f11/src/dfm/cleaning/quality_filter.py#L343">343</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/52d6d0d81c44693dd90641111493886fb22f6f11/src/dfm/cleaning/quality_filter.py#L352">352</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/52d6d0d81c44693dd90641111493886fb22f6f11/src/dfm/cleaning/quality_filter.py#L391-L406">391&ndash;406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/52d6d0d81c44693dd90641111493886fb22f6f11/src/dfm/cleaning/quality_filter.py#L539">539</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/52d6d0d81c44693dd90641111493886fb22f6f11/src/dfm/cleaning/quality_filter.py#L572-L575">572&ndash;575</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/52d6d0d81c44693dd90641111493886fb22f6f11/src/dfm/cleaning/quality_filter.py#L600">600</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/52d6d0d81c44693dd90641111493886fb22f6f11/src/dfm/cleaning/quality_filter.py#L632">632</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/52d6d0d81c44693dd90641111493886fb22f6f11/src/dfm/cleaning/quality_filter.py#L716">716</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/52d6d0d81c44693dd90641111493886fb22f6f11/src/dfm/cleaning/quality_filter.py#L730">730</a></td></tr><tr><td colspan="5"><b>src/dfm/data</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/52d6d0d81c44693dd90641111493886fb22f6f11/src/dfm/data/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/52d6d0d81c44693dd90641111493886fb22f6f11/src/dfm/data/hate_speech.py">hate_speech.py</a></td><td>11</td><td>11</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/52d6d0d81c44693dd90641111493886fb22f6f11/src/dfm/data/hate_speech.py#L1-L20">1&ndash;20</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/52d6d0d81c44693dd90641111493886fb22f6f11/src/dfm/data/load.py">load.py</a></td><td>106</td><td>91</td><td>14%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/52d6d0d81c44693dd90641111493886fb22f6f11/src/dfm/data/load.py#L35-L50">35&ndash;50</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/52d6d0d81c44693dd90641111493886fb22f6f11/src/dfm/data/load.py#L59-L83">59&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/52d6d0d81c44693dd90641111493886fb22f6f11/src/dfm/data/load.py#L98-L119">98&ndash;119</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/52d6d0d81c44693dd90641111493886fb22f6f11/src/dfm [...]

2022-06-23 06:58 UTC, KennethEnevoldsen commented
@saattrupdan I ran over previous correction again. I think I got everything, but do let me know if missed some.

2022-06-23 06:59 UTC, KennethEnevoldsen commented
<!-- Pytest Coverage Comment: pytest-coverage -->
<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/ee3d1d040aa44310f93455ad706742e283e8f153/README.md"><img alt="Coverage" src="https://img.shields.io/badge/Coverage-60%25-yellow.svg" /></a><br/><details><summary>Coverage Report</summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>src/dfm</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/ee3d1d040aa44310f93455ad706742e283e8f153/src/dfm/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/ee3d1d040aa44310f93455ad706742e283e8f153/src/dfm/train.py">train.py</a></td><td>68</td><td>68</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/ee3d1d040aa44310f93455ad706742e283e8f153/src/dfm/train.py#L14-L226">14&ndash;226</a></td></tr><tr><td colspan="5"><b>src/dfm/cleaning</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/ee3d1d040aa44310f93455ad706742e283e8f153/src/dfm/cleaning/__init__.py">__init__.py</a></td><td>2</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/ee3d1d040aa44310f93455ad706742e283e8f153/src/dfm/cleaning/deduper.py">deduper.py</a></td><td>156</td><td>16</td><td>90%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/ee3d1d040aa44310f93455ad706742e283e8f153/src/dfm/cleaning/deduper.py#L119-L124">119&ndash;124</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/ee3d1d040aa44310f93455ad706742e283e8f153/src/dfm/cleaning/deduper.py#L147">147</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/ee3d1d040aa44310f93455ad706742e283e8f153/src/dfm/cleaning/deduper.py#L275">275</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/ee3d1d040aa44310f93455ad706742e283e8f153/src/dfm/cleaning/deduper.py#L278">278</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/ee3d1d040aa44310f93455ad706742e283e8f153/src/dfm/cleaning/deduper.py#L311">311</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/ee3d1d040aa44310f93455ad706742e283e8f153/src/dfm/cleaning/deduper.py#L406">406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/ee3d1d040aa44310f93455ad706742e283e8f153/src/dfm/cleaning/deduper.py#L421">421</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/ee3d1d040aa44310f93455ad706742e283e8f153/src/dfm/cleaning/deduper.py#L444">444</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/ee3d1d040aa44310f93455ad706742e283e8f153/src/dfm/cleaning/deduper.py#L549">549</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/ee3d1d040aa44310f93455ad706742e283e8f153/src/dfm/cleaning/deduper.py#L576-L579">576&ndash;579</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/ee3d1d040aa44310f93455ad706742e283e8f153/src/dfm/cleaning/deduper_utils.py">deduper_utils.py</a></td><td>26</td><td>3</td><td>88%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/ee3d1d040aa44310f93455ad706742e283e8f153/src/dfm/cleaning/deduper_utils.py#L57-L60">57&ndash;60</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/ee3d1d040aa44310f93455ad706742e283e8f153/src/dfm/cleaning/quality_filter.py">quality_filter.py</a></td><td>220</td><td>32</td><td>85%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/ee3d1d040aa44310f93455ad706742e283e8f153/src/dfm/cleaning/quality_filter.py#L78-L83">78&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/ee3d1d040aa44310f93455ad706742e283e8f153/src/dfm/cleaning/quality_filter.py#L264">264</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/ee3d1d040aa44310f93455ad706742e283e8f153/src/dfm/cleaning/quality_filter.py#L269">269</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/ee3d1d040aa44310f93455ad706742e283e8f153/src/dfm/cleaning/quality_filter.py#L343">343</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/ee3d1d040aa44310f93455ad706742e283e8f153/src/dfm/cleaning/quality_filter.py#L352">352</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/ee3d1d040aa44310f93455ad706742e283e8f153/src/dfm/cleaning/quality_filter.py#L391-L406">391&ndash;406</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/ee3d1d040aa44310f93455ad706742e283e8f153/src/dfm/cleaning/quality_filter.py#L539">539</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/ee3d1d040aa44310f93455ad706742e283e8f153/src/dfm/cleaning/quality_filter.py#L572-L575">572&ndash;575</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/ee3d1d040aa44310f93455ad706742e283e8f153/src/dfm/cleaning/quality_filter.py#L600">600</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/ee3d1d040aa44310f93455ad706742e283e8f153/src/dfm/cleaning/quality_filter.py#L632">632</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/ee3d1d040aa44310f93455ad706742e283e8f153/src/dfm/cleaning/quality_filter.py#L716">716</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/ee3d1d040aa44310f93455ad706742e283e8f153/src/dfm/cleaning/quality_filter.py#L730">730</a></td></tr><tr><td colspan="5"><b>src/dfm/data</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/ee3d1d040aa44310f93455ad706742e283e8f153/src/dfm/data/__init__.py">__init__.py</a></td><td>1</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/ee3d1d040aa44310f93455ad706742e283e8f153/src/dfm/data/hate_speech.py">hate_speech.py</a></td><td>11</td><td>11</td><td>0%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/ee3d1d040aa44310f93455ad706742e283e8f153/src/dfm/data/hate_speech.py#L1-L20">1&ndash;20</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/ee3d1d040aa44310f93455ad706742e283e8f153/src/dfm/data/load.py">load.py</a></td><td>106</td><td>91</td><td>14%</td><td><a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/ee3d1d040aa44310f93455ad706742e283e8f153/src/dfm/data/load.py#L35-L50">35&ndash;50</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/ee3d1d040aa44310f93455ad706742e283e8f153/src/dfm/data/load.py#L59-L83">59&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/ee3d1d040aa44310f93455ad706742e283e8f153/src/dfm/data/load.py#L98-L119">98&ndash;119</a>, <a href="https://github.com/centre-for-humanities-computing/danish-foundation-models/blob/ee3d1d040aa44310f93455ad706742e283e8f153/src/dfm [...]

2022-06-23 07:13 UTC, saattrupdan approved these changes
Looks great 👍

2022-06-23 07:49 UTC, merged