Added pytest workflow for automatic testing
centre-for-humanities-computing/danish-foundation-models pull request #24
Opened 2021-12-23 18:03 UTC by KennethEnevoldsen

Added pytest workflow pr. #13 .

2022-01-07 14:23 UTC, saattrupdan requested changes
I'm guessing the files in the `dev` folder are auto-generated?

2022-01-07 14:23 UTC, saattrupdan commented on litterature.md
> +# Littererature
Typo: Literature

2022-01-07 14:23 UTC, saattrupdan commented on tests/datasets_test.py
PEP8: Needs two empty lines between global functions.

2022-01-07 14:23 UTC, saattrupdan commented on tests/datasets_test.py
PEP8: Needs two empty lines between global functions.

2022-01-07 14:23 UTC, saattrupdan commented on litterature.md
>  This is a working document for literature. This is much for sharing and organizing meterial as opposed to the Zotero which is for citation management.
Typo: material

2022-01-07 14:23 UTC, saattrupdan commented on tests/datasets_test.py
> +@pytest.mark.skip(reason="Dataset not publicly available")
PEP8: Needs two empty lines before global functions.

2022-01-07 16:03 UTC, KennethEnevoldsen commented
No the files in dev are manually added by me (copy-paste from other projects). You could essentially wrap it in a GitHub action and remove it from the codebase (which I suppose would be ideal, but would have to spend to time looking into how to write a GitHub action).

Corrected the typos and formatted them to Black. Also added a PR to check if the code style is black. We can use another style as well but had the workflow lying around for black.

2022-01-07 21:23 UTC, saattrupdan requested changes

2022-01-07 21:23 UTC, saattrupdan commented on requirements.txt
> +black
Version?

2022-01-08 09:41 UTC, KennethEnevoldsen commented on requirements.txt
> +black
Now added

2022-01-08 09:46 UTC, KennethEnevoldsen commented
@HLasse will you take a look at this when you are back from vacation? Seems like there is an issue with loading DAGW from HF hub.

This has previously been an issue with the name change, but that does not seem to be the case now. An alternative might be that it is simply not up either on HF (which I doubt) or on DAGW (which I believe is more likely).

2022-01-11 10:15 UTC, merged