Unit test deduper
centre-for-humanities-computing/danish-foundation-models pull request #47
Opened 2022-02-01 19:32 UTC by mollerhoj

Builds on top of https://github.com/centre-for-humanities-computing/danish-foundation-models/pull/46

This PR adds unittests and general improvements to the deduper.

# Code improvements (subjective)
- Extracted a few methods to make test and comprehension easier

# Features
- `silent` parameter to not print progress (useful for testing)
- `normalization_func` parameter to give user defined callback as document normalization. The old normalization has been set as the default function

# Bugfixes
- Shingles no longer forgets the last token ("abc" of char ngram size 1 becomes "a,b,c" not just "a,b")
- For documents shorter than the shingle size, we now return a single shingle ("Hej med dig" of char_ngram_size 13 becomes ["Hej med dig"] not just [].) This avoid deduplicating short but completely different documents (They would all return the same empty fingerprint).

2022-02-01 20:05 UTC, mollerhoj commented
As mentioned here: https://github.com/centre-for-humanities-computing/danish-foundation-models/discussions/45 it might makes sense to replace (or extend) the split_method to use https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.HashingVectorizer.html instead.

2022-02-02 12:00 UTC, saattrupdan requested changes
Nice one, good call with the option to change normalisation! I like the tests as well, especially the "miss-tests" when varying the minhash byte size, good idea 😊

2022-02-02 20:15 UTC, mollerhoj commented on tests/cleaning/deduper_test.py
> +    def deduper(self, **kwargs):
The efficiency gains here will be neglectable, but I appreciate if it's more idiomatic. I wouldn't wanna sacrifice the conciseness of individual unit tests though.

I'm not sure I understand though: `deduper.ngram_size = 13` is an assignment *after* initialization?

Feel free to add commits to this PR if you wanna demonstrate.

2022-02-04 15:18 UTC, saattrupdan requested changes
Let's get this PR sorted. There's a single import bug, and you need to insert (blank) `__init__.py` scripts in the subfolders of the `tests` folders, as otherwise `pytest` doesn't know how to import scripts. Otherwise, I think it's fine 🙂

2022-02-04 15:18 UTC, saattrupdan commented on dfm/cleaning/deduper.py
> +from collections.abc import Callable
This should be imported from `typing` instead (causing an error on my side):

2022-02-09 21:26 UTC, merged