quality filter cleanup
centre-for-humanities-computing/danish-foundation-models pull request #49
Opened 2022-02-02 21:20 UTC by mollerhoj

- rearrange tests to follow library structure
- consistency between file and class name
- split fixtures and tests into individual units
- do not allow variable abbreviations
- run black

2022-02-03 08:17 UTC, KennethEnevoldsen requested changes
Looks good to me. I would say with this rewrite you don't use the class at all so you might as well remove it. @saattrupdan is there any benefit of having the class which I am unaware of?

2022-02-03 08:17 UTC, KennethEnevoldsen commented on tests/cleaning/quality_filter_test.py
> +        """
This is also a bullet point text (ellipsis is the ...)

2022-02-03 08:41 UTC, KennethEnevoldsen requested changes
I read through it again, there are probably a few more clean up steps to do.

2022-02-03 08:41 UTC, KennethEnevoldsen commented on tests/cleaning/quality_filter_test.py
> +    def long_text(self):
```suggestion
    def valid_text(self):
```
Is probably more descriptive

2022-02-03 08:41 UTC, KennethEnevoldsen commented on tests/cleaning/quality_filter_test.py
> +        )
Might as well test with all short texts splitting them into valid/invalid

2022-02-03 08:41 UTC, KennethEnevoldsen commented on tests/cleaning/quality_filter_test.py
> +        )
test on long text as well

2022-02-03 08:41 UTC, KennethEnevoldsen commented on tests/cleaning/quality_filter_test.py
> +        )
Again this is False because of the bullet point part, not the ellipsis part (i.e. this and the next test just test two different types of bullets)

2022-02-03 08:41 UTC, KennethEnevoldsen commented on tests/cleaning/quality_filter_test.py
> +        )
This is basically a copy of the next test you can simplify it using `pytest.mark.parametrize `
```suggestion
    @pytest.mark.parametrize(
    "text,valid",
    [
        ("jeg er glad...", False),
        ("jeg er glad…", False),
    ],
    )
    def test_bad_ellipsis_dots(self, quality_filter, text, valid):
        assert (
            quality_filter.line_bullets_or_ellipsis(
                quality_filter.nlp("jeg er glad…"),
                max_p_bullets=1.0,
                max_p_ellipsis=0.5,
            )
            is valid
        )
```

2022-02-03 10:42 UTC, saattrupdan commented
> Looks very good. I would say with this rewrite you don't use the class so you might as well remove it. @saattrupdan is there any benefit of having the class which I am unaware of?

@KennethEnevoldsen It's basically a matter of organisation, and there are multiple ways of doing that. It seems that we're sticking to the "one test script for each script", in which case it makes sense to be able to group the tests in the individual test scripts. As an added benefit, we can treat these groups (=classes) as one unit: disable all at once, use `pytest.parametrize` to add more test cases to all tests in a class, subclass etc.

2022-02-03 12:34 UTC, KennethEnevoldsen commented
Ahh perfect, thanks for the clarification. Yea so probably good to keep the test of the entire class in a class just to group it.

2022-02-03 14:44 UTC, mollerhoj commented
I generally agreed with this review. However do note that the scope of this PR is cleaning up *without* changing the semantics for the tests. Further improvements should be in separate subsequent PRs, so I will ignore those comments here.

2022-02-09 11:11 UTC, KennethEnevoldsen commented
I have merged this into #54, where I made some changes to the quality filter. I also updated the test with the above-mentioned. @mollerhoj I have added you as a reviewer to that one to ensure consistency.

2022-02-09 11:11 UTC, closed without merging